using System;

namespace AKNet.Udp5MSQuic.Common
{
    public enum QuicEventId : ushort
    {
        LibraryInitialized = 1,
        LibraryUninitialized,
        LibraryAddRef,
        LibraryRelease,
        LibraryServerInit,
        AllocFailure,
        LibraryRundown,
        LibraryError,
        LibraryErrorStatus,
        LibraryAssert,
        ApiEnter,
        ApiExit,
        ApiExitStatus,
        ApiWaitOperation,
        PerfCountersRundown,
        LibrarySendRetryStateUpdated,
        LibraryVersion,
        LibraryInitializedV2,
        DataPathInitialized,
        LibraryRundownV2,
        DataPathRundown,

        RegistrationCreated = 1024,
        RegistrationDestroyed,
        RegistrationCleanup,
        RegistrationRundown,
        RegistrationError,
        RegistrationErrorStatus,
        RegistrationShutdown,
        RegistrationCreatedV2,
        RegistrationRundownV2,

        WorkerCreated = 2048,
        WorkerStart,
        WorkerStop,
        WorkerActivityStateUpdated,
        WorkerQueueDelayUpdated,
        WorkerDestroyed,
        WorkerCleanup,
        WorkerError,
        WorkerErrorStatus,

        ConfigurationCreated = 3072,
        ConfigurationDestroyed,
        ConfigurationCleanup,
        QuicConfigurationRundown = 3076,
        ConfigurationError,
        QuicConfigurationErrorStatus,

        ListenerCreated = 4096,
        ListenerDestroyed,
        ListenerStarted,
        ListenerStopped,
        ListenerRundown,
        ListenerError,
        ListenerErrorStatus,

        ConnCreated = 5120,
        ConnDestroyed,
        ConnHandshakeComplete,
        ConnScheduleState,
        ConnExecOper,
        ConnExecApiOper,
        ConnExecTimerOper,
        ConnLocalAddrAdded,
        ConnRemoteAddrAdded,
        ConnLocalAddrRemoved,
        ConnRemoteAddrRemoved,
        ConnAssignWorker,
        ConnHandshakeStart,
        ConnRegisterSession,
        ConnUnregisterSession,
        ConnTransportShutdown,
        ConnAppShutdown,
        ConnInitializeComplete,
        ConnHandleClosed,
        ConnVersionSet,
        ConnOutFlowStats,
        ConnOutFlowBlocked,
        ConnInFlowStats,
        ConnCubic,
        ConnCongestion,
        ConnPersistentCongestion,
        ConnRecoveryExit,
        ConnRundown,
        ConnSourceCidAdded,
        ConnDestCidAdded,
        ConnSourceCidRemoved,
        ConnDestCidRemoved,
        ConnLossDetectionTimerSet,
        ConnLossDetectionTimerCancel,
        ConnDropPacket,
        ConnDropPacketEx,
        ConnError,
        ConnErrorStatus,
        ConnNewPacketKeys,
        ConnKeyPhaseChange,
        ConnStats,
        ConnShutdownComplete,
        ConnReadKeyUpdated,
        ConnWriteKeyUpdated,
        ConnPacketSent,
        ConnPacketRecv,
        ConnPacketLost,
        ConnPacketACKed,
        ConnLogError,
        ConnLogWarning,
        ConnLogInfo,
        ConnLogVerbose,
        ConnQueueSendFlush,
        ConnOutFlowStreamStats,
        ConnPacketStats,
        ConnServerResumeTicket,
        ConnVNEOtherVersionList,
        ConnClientReceivedVersionList,
        ConnServerSupportedVersionList,
        ConnSpuriousCongestion,
        ConnNoListenerIp,
        ConnNoListenerAlpn,
        ConnFlushSend,
        ConnTimerSet,
        ConnTimerCancel,
        ConnTimerExpire,
        ConnBbr,
        ConnEcnCapable,
        ConnEcnFailed,
        ConnCongestionV2,
        ConnStatsV2,
        ConnCubicHyStart,
        ConnRecvUdpDatagrams,
        ConnOutFlowStatsV2,
        ConnStatsV3,

        StreamCreated = 6144,
        StreamDestroyed,
        StreamOutFlowBlocked,
        StreamRundown,
        StreamSendState,
        StreamRecvState,
        StreamError,
        StreamErrorStatus,
        StreamLogError,
        StreamLogWarning,
        StreamLogInfo,
        StreamLogVerbose,
        StreamAlloc,
        StreamWriteFrames,
        StreamReceiveFrame,
        StreamAppReceive,
        StreamAppReceiveComplete,
        StreamAppSend,
        StreamReceiveFrameComplete,
        StreamAppReceiveCompleteCall,

        BindingCreated = 7168,
        BindingRundown,
        BindingDestroyed,
        BindingCleanup,
        BindingDropPacket,
        BindingDropPacketEx,
        BindingError,
        BindingErrorStatus,
        BindingExecOper,

        TlsError = 8192,
        TlsErrorStatus,
        TlsMessage,

        Temporal = 9216, // Temporary, while there are still builds out there generating this old event
        DatapathSend,
        DatapathRecv,
        DatapathError,
        DatapathErrorStatus,
        DatapathCreated,
        DatapathDestroyed,

        LogError = 10240,
        LogWarning,
        LogInfo,
        LogVerbose,

        PacketCreated = 11264,
        PacketEncrypt,
        PacketFinalize,
        PacketBatchSent,
        PacketReceive,
        PacketDecrypt
    }
}
