#include <openssl/ssl.h>
#include <openssl/ssl2.h>
#include <openssl/ssl3.h>
#include <openssl/err.h>
#include <openssl/quic.h>
#include <new>

struct srtp_protection_profile_st& (srtp_protection_profile_st::*_0)(struct srtp_protection_profile_st&&) = &srtp_protection_profile_st::operator=;
struct ssl_shutdown_ex_args_st& (ssl_shutdown_ex_args_st::*_1)(struct ssl_shutdown_ex_args_st&&) = &ssl_shutdown_ex_args_st::operator=;
struct ssl_stream_reset_args_st& (ssl_stream_reset_args_st::*_2)(struct ssl_stream_reset_args_st&&) = &ssl_stream_reset_args_st::operator=;
struct ssl_conn_close_info_st& (ssl_conn_close_info_st::*_3)(struct ssl_conn_close_info_st&&) = &ssl_conn_close_info_st::operator=;
struct ssl_poll_item_st& (ssl_poll_item_st::*_4)(struct ssl_poll_item_st&&) = &ssl_poll_item_st::operator=;
struct srtp_protection_profile_st* (*_5)(struct srtp_protection_profile_st*) = &::ossl_check_SRTP_PROTECTION_PROFILE_type;
const struct stack_st* (*_6)(const struct stack_st_SRTP_PROTECTION_PROFILE*) = &::ossl_check_const_SRTP_PROTECTION_PROFILE_sk_type;
struct stack_st* (*_7)(struct stack_st_SRTP_PROTECTION_PROFILE*) = &::ossl_check_SRTP_PROTECTION_PROFILE_sk_type;
int (* (*_8)(int (*)(const struct srtp_protection_profile_st* const*, const struct srtp_protection_profile_st* const*)))(const void*, const void*) = &::ossl_check_SRTP_PROTECTION_PROFILE_compfunc_type;
void* (* (*_9)(struct srtp_protection_profile_st* (*)(const struct srtp_protection_profile_st*)))(const void*) = &::ossl_check_SRTP_PROTECTION_PROFILE_copyfunc_type;
void (* (*_10)(void (*)(struct srtp_protection_profile_st*)))(void*) = &::ossl_check_SRTP_PROTECTION_PROFILE_freefunc_type;
const struct ssl_cipher_st* (*_11)(const struct ssl_cipher_st*) = &::ossl_check_SSL_CIPHER_type;
const struct stack_st* (*_12)(const struct stack_st_SSL_CIPHER*) = &::ossl_check_const_SSL_CIPHER_sk_type;
struct stack_st* (*_13)(struct stack_st_SSL_CIPHER*) = &::ossl_check_SSL_CIPHER_sk_type;
int (* (*_14)(int (*)(const struct ssl_cipher_st* const*, const struct ssl_cipher_st* const*)))(const void*, const void*) = &::ossl_check_SSL_CIPHER_compfunc_type;
void* (* (*_15)(struct ssl_cipher_st* (*)(const struct ssl_cipher_st*)))(const void*) = &::ossl_check_SSL_CIPHER_copyfunc_type;
void (* (*_16)(void (*)(struct ssl_cipher_st*)))(void*) = &::ossl_check_SSL_CIPHER_freefunc_type;
struct bio_poll_descriptor_st (*_17)(struct ssl_st*) = &::SSL_as_poll_descriptor;
char* (*_18)(char*) = &::ossl_check_OPENSSL_STRING_type;
const struct stack_st* (*_19)(const struct stack_st_OPENSSL_STRING*) = &::ossl_check_const_OPENSSL_STRING_sk_type;
struct stack_st* (*_20)(struct stack_st_OPENSSL_STRING*) = &::ossl_check_OPENSSL_STRING_sk_type;
int (* (*_21)(int (*)(const char* const*, const char* const*)))(const void*, const void*) = &::ossl_check_OPENSSL_STRING_compfunc_type;
void* (* (*_22)(char* (*)(const char*)))(const void*) = &::ossl_check_OPENSSL_STRING_copyfunc_type;
void (* (*_23)(void (*)(char*)))(void*) = &::ossl_check_OPENSSL_STRING_freefunc_type;
const char* (*_24)(const char*) = &::ossl_check_OPENSSL_CSTRING_type;
const struct stack_st* (*_25)(const struct stack_st_OPENSSL_CSTRING*) = &::ossl_check_const_OPENSSL_CSTRING_sk_type;
struct stack_st* (*_26)(struct stack_st_OPENSSL_CSTRING*) = &::ossl_check_OPENSSL_CSTRING_sk_type;
int (* (*_27)(int (*)(const char* const*, const char* const*)))(const void*, const void*) = &::ossl_check_OPENSSL_CSTRING_compfunc_type;
void* (* (*_28)(char* (*)(const char*)))(const void*) = &::ossl_check_OPENSSL_CSTRING_copyfunc_type;
void (* (*_29)(void (*)(char*)))(void*) = &::ossl_check_OPENSSL_CSTRING_freefunc_type;
void* (*_30)(void*) = &::ossl_check_OPENSSL_BLOCK_type;
const struct stack_st* (*_31)(const struct stack_st_OPENSSL_BLOCK*) = &::ossl_check_const_OPENSSL_BLOCK_sk_type;
struct stack_st* (*_32)(struct stack_st_OPENSSL_BLOCK*) = &::ossl_check_OPENSSL_BLOCK_sk_type;
int (* (*_33)(int (*)(const void* const*, const void* const*)))(const void*, const void*) = &::ossl_check_OPENSSL_BLOCK_compfunc_type;
void* (* (*_34)(void* (*)(const void*)))(const void*) = &::ossl_check_OPENSSL_BLOCK_copyfunc_type;
void (* (*_35)(void (*)(void*)))(void*) = &::ossl_check_OPENSSL_BLOCK_freefunc_type;
struct ossl_dispatch_st& (ossl_dispatch_st::*_36)(struct ossl_dispatch_st&&) = &ossl_dispatch_st::operator=;
struct ossl_item_st& (ossl_item_st::*_37)(struct ossl_item_st&&) = &ossl_item_st::operator=;
struct ossl_algorithm_st& (ossl_algorithm_st::*_38)(struct ossl_algorithm_st&&) = &ossl_algorithm_st::operator=;
struct ossl_param_st& (ossl_param_st::*_39)(struct ossl_param_st&&) = &ossl_param_st::operator=;
CRYPTO_dynlock& (CRYPTO_dynlock::*_40)(CRYPTO_dynlock&&) = &CRYPTO_dynlock::operator=;
struct crypto_ex_data_st& (crypto_ex_data_st::*_41)(struct crypto_ex_data_st&&) = &crypto_ex_data_st::operator=;
struct crypto_threadid_st& (crypto_threadid_st::*_42)(struct crypto_threadid_st&&) = &crypto_threadid_st::operator=;
void* (*_43)(void*) = &::ossl_check_void_type;
const struct stack_st* (*_44)(const struct stack_st_void*) = &::ossl_check_const_void_sk_type;
struct stack_st* (*_45)(struct stack_st_void*) = &::ossl_check_void_sk_type;
int (* (*_46)(int (*)(const void* const*, const void* const*)))(const void*, const void*) = &::ossl_check_void_compfunc_type;
void* (* (*_47)(void* (*)(const void*)))(const void*) = &::ossl_check_void_copyfunc_type;
void (* (*_48)(void (*)(void*)))(void*) = &::ossl_check_void_freefunc_type;
struct ssl_comp_st* (*_49)(struct ssl_comp_st*) = &::ossl_check_SSL_COMP_type;
const struct stack_st* (*_50)(const struct stack_st_SSL_COMP*) = &::ossl_check_const_SSL_COMP_sk_type;
struct stack_st* (*_51)(struct stack_st_SSL_COMP*) = &::ossl_check_SSL_COMP_sk_type;
int (* (*_52)(int (*)(const struct ssl_comp_st* const*, const struct ssl_comp_st* const*)))(const void*, const void*) = &::ossl_check_SSL_COMP_compfunc_type;
void* (* (*_53)(struct ssl_comp_st* (*)(const struct ssl_comp_st*)))(const void*) = &::ossl_check_SSL_COMP_copyfunc_type;
void (* (*_54)(void (*)(struct ssl_comp_st*)))(void*) = &::ossl_check_SSL_COMP_freefunc_type;
struct bio_msg_st& (bio_msg_st::*_55)(struct bio_msg_st&&) = &bio_msg_st::operator=;
struct bio_mmsg_cb_args_st& (bio_mmsg_cb_args_st::*_56)(struct bio_mmsg_cb_args_st&&) = &bio_mmsg_cb_args_st::operator=;
struct bio_poll_descriptor_st& (bio_poll_descriptor_st::*_57)(struct bio_poll_descriptor_st&&) = &bio_poll_descriptor_st::operator=;
union BIO_sock_info_u& (BIO_sock_info_u::*_58)(union BIO_sock_info_u&&) = &BIO_sock_info_u::operator=;
struct bio_st* (*_59)(struct bio_st*) = &::ossl_check_BIO_type;
const struct stack_st* (*_60)(const struct stack_st_BIO*) = &::ossl_check_const_BIO_sk_type;
struct stack_st* (*_61)(struct stack_st_BIO*) = &::ossl_check_BIO_sk_type;
int (* (*_62)(int (*)(const struct bio_st* const*, const struct bio_st* const*)))(const void*, const void*) = &::ossl_check_BIO_compfunc_type;
void* (* (*_63)(struct bio_st* (*)(const struct bio_st*)))(const void*) = &::ossl_check_BIO_copyfunc_type;
void (* (*_64)(void (*)(struct bio_st*)))(void*) = &::ossl_check_BIO_freefunc_type;
struct buf_mem_st& (buf_mem_st::*_65)(struct buf_mem_st&&) = &buf_mem_st::operator=;
const struct ossl_param_st* (* (*_66)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_gettable_params;
int (* (*_67)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, struct ossl_param_st[]) = &::OSSL_FUNC_core_get_params;
int (* (*_68)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, void (*)(void*), void*) = &::OSSL_FUNC_core_thread_start;
struct openssl_core_ctx_st* (* (*_69)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_get_libctx;
void (* (*_70)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_new_error;
void (* (*_71)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, const char*, int, const char*) = &::OSSL_FUNC_core_set_error_debug;
int (* (*_72)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_set_error_mark;
int (* (*_73)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_clear_last_error_mark;
int (* (*_74)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_pop_error_to_mark;
int (* (*_75)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, const char*, const char*, const char*) = &::OSSL_FUNC_core_obj_add_sigid;
int (* (*_76)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, const char*, const char*, const char*) = &::OSSL_FUNC_core_obj_create;
void* (* (*_77)(const struct ossl_dispatch_st*))(unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_malloc;
void* (* (*_78)(const struct ossl_dispatch_st*))(unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_zalloc;
void (* (*_79)(const struct ossl_dispatch_st*))(void*, const char*, int) = &::OSSL_FUNC_CRYPTO_free;
void (* (*_80)(const struct ossl_dispatch_st*))(void*, unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_clear_free;
void* (* (*_81)(const struct ossl_dispatch_st*))(void*, unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_realloc;
void* (* (*_82)(const struct ossl_dispatch_st*))(void*, unsigned long long, unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_clear_realloc;
void* (* (*_83)(const struct ossl_dispatch_st*))(unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_secure_malloc;
void* (* (*_84)(const struct ossl_dispatch_st*))(unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_secure_zalloc;
void (* (*_85)(const struct ossl_dispatch_st*))(void*, const char*, int) = &::OSSL_FUNC_CRYPTO_secure_free;
void (* (*_86)(const struct ossl_dispatch_st*))(void*, unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_secure_clear_free;
int (* (*_87)(const struct ossl_dispatch_st*))(const void*) = &::OSSL_FUNC_CRYPTO_secure_allocated;
void (* (*_88)(const struct ossl_dispatch_st*))(void*, unsigned long long) = &::OSSL_FUNC_OPENSSL_cleanse;
struct ossl_core_bio_st* (* (*_89)(const struct ossl_dispatch_st*))(const char*, const char*) = &::OSSL_FUNC_BIO_new_file;
struct ossl_core_bio_st* (* (*_90)(const struct ossl_dispatch_st*))(const void*, int) = &::OSSL_FUNC_BIO_new_membuf;
int (* (*_91)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*, void*, unsigned long long, unsigned long long*) = &::OSSL_FUNC_BIO_read_ex;
int (* (*_92)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*, const void*, unsigned long long, unsigned long long*) = &::OSSL_FUNC_BIO_write_ex;
int (* (*_93)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*, char*, int) = &::OSSL_FUNC_BIO_gets;
int (* (*_94)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*, const char*) = &::OSSL_FUNC_BIO_puts;
int (* (*_95)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*) = &::OSSL_FUNC_BIO_up_ref;
int (* (*_96)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*) = &::OSSL_FUNC_BIO_free;
int (* (*_97)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*, int, long, void*) = &::OSSL_FUNC_BIO_ctrl;
void (* (*_98)(const struct ossl_dispatch_st*))(struct openssl_core_ctx_st*, int (**)(const char*, const char*, struct ossl_param_st[])) = &::OSSL_FUNC_indicator_cb;
void (* (*_99)(const struct ossl_dispatch_st*))(struct openssl_core_ctx_st*, int (**)(struct ossl_param_st[], void*), void**) = &::OSSL_FUNC_self_test_cb;
unsigned long long (* (*_100)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char**, int, unsigned long long, unsigned long long) = &::OSSL_FUNC_get_entropy;
unsigned long long (* (*_101)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char**, int, unsigned long long, unsigned long long) = &::OSSL_FUNC_get_user_entropy;
void (* (*_102)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char*, unsigned long long) = &::OSSL_FUNC_cleanup_entropy;
void (* (*_103)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char*, unsigned long long) = &::OSSL_FUNC_cleanup_user_entropy;
unsigned long long (* (*_104)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char**, unsigned long long, unsigned long long, const void*, unsigned long long) = &::OSSL_FUNC_get_nonce;
unsigned long long (* (*_105)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char**, unsigned long long, unsigned long long, const void*, unsigned long long) = &::OSSL_FUNC_get_user_nonce;
void (* (*_106)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char*, unsigned long long) = &::OSSL_FUNC_cleanup_nonce;
void (* (*_107)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char*, unsigned long long) = &::OSSL_FUNC_cleanup_user_nonce;
int (* (*_108)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, int (*)(const struct ossl_core_handle_st*, void*), int (*)(const struct ossl_core_handle_st*, void*), int (*)(const char*, void*), void*) = &::OSSL_FUNC_provider_register_child_cb;
void (* (*_109)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_provider_deregister_child_cb;
const char* (* (*_110)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_provider_name;
void* (* (*_111)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_provider_get0_provider_ctx;
const struct ossl_dispatch_st* (* (*_112)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_provider_get0_dispatch;
int (* (*_113)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, int) = &::OSSL_FUNC_provider_up_ref;
int (* (*_114)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, int) = &::OSSL_FUNC_provider_free;
void (* (*_115)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_provider_teardown;
const struct ossl_param_st* (* (*_116)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_provider_gettable_params;
int (* (*_117)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_provider_get_params;
const struct ossl_algorithm_st* (* (*_118)(const struct ossl_dispatch_st*))(void*, int, int*) = &::OSSL_FUNC_provider_query_operation;
void (* (*_119)(const struct ossl_dispatch_st*))(void*, int, const struct ossl_algorithm_st*) = &::OSSL_FUNC_provider_unquery_operation;
const struct ossl_item_st* (* (*_120)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_provider_get_reason_strings;
int (* (*_121)(const struct ossl_dispatch_st*))(void*, const char*, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_provider_get_capabilities;
int (* (*_122)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_provider_self_test;
int (* (*_123)(const struct ossl_dispatch_st*))(void*, int, void*, unsigned long long, unsigned int) = &::OSSL_FUNC_provider_random_bytes;
int (* (*_124)(const struct ossl_dispatch_st*))(struct ssl_st*, const unsigned char*, unsigned long long, unsigned long long*, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_crypto_send;
int (* (*_125)(const struct ossl_dispatch_st*))(struct ssl_st*, const unsigned char**, unsigned long long*, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_crypto_recv_rcd;
int (* (*_126)(const struct ossl_dispatch_st*))(struct ssl_st*, unsigned long long, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_crypto_release_rcd;
int (* (*_127)(const struct ossl_dispatch_st*))(struct ssl_st*, unsigned int, int, const unsigned char*, unsigned long long, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_yield_secret;
int (* (*_128)(const struct ossl_dispatch_st*))(struct ssl_st*, const unsigned char*, unsigned long long, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_got_transport_params;
int (* (*_129)(const struct ossl_dispatch_st*))(struct ssl_st*, unsigned char, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_alert;
void* (* (*_130)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_digest_newctx;
int (* (*_131)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_digest_init;
int (* (*_132)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_digest_update;
int (* (*_133)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_digest_final;
int (* (*_134)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_digest_squeeze;
int (* (*_135)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_digest_digest;
void (* (*_136)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_digest_freectx;
void* (* (*_137)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_digest_dupctx;
void (* (*_138)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_digest_copyctx;
int (* (*_139)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_digest_get_params;
int (* (*_140)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_digest_set_ctx_params;
int (* (*_141)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_digest_get_ctx_params;
const struct ossl_param_st* (* (*_142)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_digest_gettable_params;
const struct ossl_param_st* (* (*_143)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_digest_settable_ctx_params;
const struct ossl_param_st* (* (*_144)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_digest_gettable_ctx_params;
void* (* (*_145)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_cipher_newctx;
int (* (*_146)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_encrypt_init;
int (* (*_147)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_decrypt_init;
int (* (*_148)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_cipher_update;
int (* (*_149)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_cipher_final;
int (* (*_150)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_cipher_cipher;
int (* (*_151)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, unsigned long long, const unsigned char**, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_pipeline_encrypt_init;
int (* (*_152)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, unsigned long long, const unsigned char**, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_pipeline_decrypt_init;
int (* (*_153)(const struct ossl_dispatch_st*))(void*, unsigned long long, unsigned char**, unsigned long long*, const unsigned long long*, const unsigned char**, const unsigned long long*) = &::OSSL_FUNC_cipher_pipeline_update;
int (* (*_154)(const struct ossl_dispatch_st*))(void*, unsigned long long, unsigned char**, unsigned long long*, const unsigned long long*) = &::OSSL_FUNC_cipher_pipeline_final;
void (* (*_155)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_cipher_freectx;
void* (* (*_156)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_cipher_dupctx;
int (* (*_157)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_cipher_get_params;
int (* (*_158)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_get_ctx_params;
int (* (*_159)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_set_ctx_params;
const struct ossl_param_st* (* (*_160)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_cipher_gettable_params;
const struct ossl_param_st* (* (*_161)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_cipher_settable_ctx_params;
const struct ossl_param_st* (* (*_162)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_cipher_gettable_ctx_params;
int (* (*_163)(const struct ossl_dispatch_st*))(void*, void*, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_encrypt_skey_init;
int (* (*_164)(const struct ossl_dispatch_st*))(void*, void*, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_decrypt_skey_init;
void* (* (*_165)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_mac_newctx;
void* (* (*_166)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_mac_dupctx;
void (* (*_167)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_mac_freectx;
int (* (*_168)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_mac_init;
int (* (*_169)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_mac_update;
int (* (*_170)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_mac_final;
const struct ossl_param_st* (* (*_171)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_mac_gettable_params;
const struct ossl_param_st* (* (*_172)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_mac_gettable_ctx_params;
const struct ossl_param_st* (* (*_173)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_mac_settable_ctx_params;
int (* (*_174)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_mac_get_params;
int (* (*_175)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_mac_get_ctx_params;
int (* (*_176)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_mac_set_ctx_params;
int (* (*_177)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_mac_init_skey;
void* (* (*_178)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kdf_newctx;
void* (* (*_179)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kdf_dupctx;
void (* (*_180)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kdf_freectx;
void (* (*_181)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kdf_reset;
int (* (*_182)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_kdf_derive;
const struct ossl_param_st* (* (*_183)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kdf_gettable_params;
const struct ossl_param_st* (* (*_184)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_kdf_gettable_ctx_params;
const struct ossl_param_st* (* (*_185)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_kdf_settable_ctx_params;
int (* (*_186)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_kdf_get_params;
int (* (*_187)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_kdf_get_ctx_params;
int (* (*_188)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_kdf_set_ctx_params;
void* (* (*_189)(const struct ossl_dispatch_st*))(void*, void*, const struct ossl_dispatch_st*) = &::OSSL_FUNC_rand_newctx;
void (* (*_190)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_freectx;
int (* (*_191)(const struct ossl_dispatch_st*))(void*, unsigned int, int, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_rand_instantiate;
int (* (*_192)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_uninstantiate;
int (* (*_193)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long, unsigned int, int, const unsigned char*, unsigned long long) = &::OSSL_FUNC_rand_generate;
int (* (*_194)(const struct ossl_dispatch_st*))(void*, int, const unsigned char*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_rand_reseed;
unsigned long long (* (*_195)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned int, unsigned long long, unsigned long long) = &::OSSL_FUNC_rand_nonce;
int (* (*_196)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_enable_locking;
int (* (*_197)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_lock;
void (* (*_198)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_unlock;
const struct ossl_param_st* (* (*_199)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_gettable_params;
const struct ossl_param_st* (* (*_200)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_rand_gettable_ctx_params;
const struct ossl_param_st* (* (*_201)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_rand_settable_ctx_params;
int (* (*_202)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_rand_get_params;
int (* (*_203)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_rand_get_ctx_params;
int (* (*_204)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_rand_set_ctx_params;
void (* (*_205)(const struct ossl_dispatch_st*))(void*, int (*)(struct ossl_param_st[], struct ossl_param_st[], void*), int (*)(struct ossl_param_st[], void*), int (*)(struct ossl_param_st[], struct ossl_param_st[], void*), int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_rand_set_callbacks;
int (* (*_206)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_verify_zeroization;
unsigned long long (* (*_207)(const struct ossl_dispatch_st*))(void*, unsigned char**, int, unsigned long long, unsigned long long, int, const unsigned char*, unsigned long long) = &::OSSL_FUNC_rand_get_seed;
void (* (*_208)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long) = &::OSSL_FUNC_rand_clear_seed;
void* (* (*_209)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keymgmt_new;
void* (* (*_210)(const struct ossl_dispatch_st*))(void*, int, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_gen_init;
int (* (*_211)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keymgmt_gen_set_template;
int (* (*_212)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_gen_set_params;
const struct ossl_param_st* (* (*_213)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keymgmt_gen_settable_params;
int (* (*_214)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_gen_get_params;
const struct ossl_param_st* (* (*_215)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keymgmt_gen_gettable_params;
void* (* (*_216)(const struct ossl_dispatch_st*))(void*, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_keymgmt_gen;
void (* (*_217)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keymgmt_gen_cleanup;
void* (* (*_218)(const struct ossl_dispatch_st*))(const void*, unsigned long long) = &::OSSL_FUNC_keymgmt_load;
void (* (*_219)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keymgmt_free;
int (* (*_220)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_get_params;
const struct ossl_param_st* (* (*_221)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keymgmt_gettable_params;
int (* (*_222)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_set_params;
const struct ossl_param_st* (* (*_223)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keymgmt_settable_params;
const char* (* (*_224)(const struct ossl_dispatch_st*))(int) = &::OSSL_FUNC_keymgmt_query_operation_name;
int (* (*_225)(const struct ossl_dispatch_st*))(const void*, int) = &::OSSL_FUNC_keymgmt_has;
int (* (*_226)(const struct ossl_dispatch_st*))(const void*, int, int) = &::OSSL_FUNC_keymgmt_validate;
int (* (*_227)(const struct ossl_dispatch_st*))(const void*, const void*, int) = &::OSSL_FUNC_keymgmt_match;
int (* (*_228)(const struct ossl_dispatch_st*))(void*, int, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_import;
const struct ossl_param_st* (* (*_229)(const struct ossl_dispatch_st*))(int) = &::OSSL_FUNC_keymgmt_import_types;
int (* (*_230)(const struct ossl_dispatch_st*))(void*, int, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_keymgmt_export;
const struct ossl_param_st* (* (*_231)(const struct ossl_dispatch_st*))(int) = &::OSSL_FUNC_keymgmt_export_types;
void* (* (*_232)(const struct ossl_dispatch_st*))(const void*, int) = &::OSSL_FUNC_keymgmt_dup;
const struct ossl_param_st* (* (*_233)(const struct ossl_dispatch_st*))(void*, int) = &::OSSL_FUNC_keymgmt_import_types_ex;
const struct ossl_param_st* (* (*_234)(const struct ossl_dispatch_st*))(void*, int) = &::OSSL_FUNC_keymgmt_export_types_ex;
void* (* (*_235)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keyexch_newctx;
int (* (*_236)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_keyexch_init;
int (* (*_237)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_keyexch_derive;
int (* (*_238)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keyexch_set_peer;
void (* (*_239)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keyexch_freectx;
void* (* (*_240)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keyexch_dupctx;
int (* (*_241)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keyexch_set_ctx_params;
const struct ossl_param_st* (* (*_242)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keyexch_settable_ctx_params;
int (* (*_243)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keyexch_get_ctx_params;
const struct ossl_param_st* (* (*_244)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keyexch_gettable_ctx_params;
void* (* (*_245)(const struct ossl_dispatch_st*))(void*, const char*) = &::OSSL_FUNC_signature_newctx;
int (* (*_246)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_sign_init;
int (* (*_247)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_sign;
int (* (*_248)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_sign_message_init;
int (* (*_249)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_sign_message_update;
int (* (*_250)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_signature_sign_message_final;
int (* (*_251)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_verify_init;
int (* (*_252)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_verify;
int (* (*_253)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_verify_message_init;
int (* (*_254)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_verify_message_update;
int (* (*_255)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_signature_verify_message_final;
int (* (*_256)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_verify_recover_init;
int (* (*_257)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_verify_recover;
int (* (*_258)(const struct ossl_dispatch_st*))(void*, const char*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_digest_sign_init;
int (* (*_259)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_digest_sign_update;
int (* (*_260)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_signature_digest_sign_final;
int (* (*_261)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_digest_sign;
int (* (*_262)(const struct ossl_dispatch_st*))(void*, const char*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_digest_verify_init;
int (* (*_263)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_digest_verify_update;
int (* (*_264)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_digest_verify_final;
int (* (*_265)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_digest_verify;
void (* (*_266)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_signature_freectx;
void* (* (*_267)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_signature_dupctx;
int (* (*_268)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_get_ctx_params;
const struct ossl_param_st* (* (*_269)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_signature_gettable_ctx_params;
int (* (*_270)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_set_ctx_params;
const struct ossl_param_st* (* (*_271)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_signature_settable_ctx_params;
int (* (*_272)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_get_ctx_md_params;
const struct ossl_param_st* (* (*_273)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_signature_gettable_ctx_md_params;
int (* (*_274)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_set_ctx_md_params;
const struct ossl_param_st* (* (*_275)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_signature_settable_ctx_md_params;
const char** (* (*_276)(const struct ossl_dispatch_st*))() = &::OSSL_FUNC_signature_query_key_types;
void (* (*_277)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_skeymgmt_free;
const struct ossl_param_st* (* (*_278)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_skeymgmt_imp_settable_params;
void* (* (*_279)(const struct ossl_dispatch_st*))(void*, int, struct ossl_param_st[]) = &::OSSL_FUNC_skeymgmt_import;
int (* (*_280)(const struct ossl_dispatch_st*))(void*, int, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_skeymgmt_export;
const struct ossl_param_st* (* (*_281)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_skeymgmt_gen_settable_params;
void* (* (*_282)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_skeymgmt_generate;
const char* (* (*_283)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_skeymgmt_get_key_id;
void* (* (*_284)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_asym_cipher_newctx;
int (* (*_285)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_asym_cipher_encrypt_init;
int (* (*_286)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_asym_cipher_encrypt;
int (* (*_287)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_asym_cipher_decrypt_init;
int (* (*_288)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_asym_cipher_decrypt;
void (* (*_289)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_asym_cipher_freectx;
void* (* (*_290)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_asym_cipher_dupctx;
int (* (*_291)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_asym_cipher_get_ctx_params;
const struct ossl_param_st* (* (*_292)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_asym_cipher_gettable_ctx_params;
int (* (*_293)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_asym_cipher_set_ctx_params;
const struct ossl_param_st* (* (*_294)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_asym_cipher_settable_ctx_params;
void* (* (*_295)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kem_newctx;
int (* (*_296)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_encapsulate_init;
int (* (*_297)(const struct ossl_dispatch_st*))(void*, void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_auth_encapsulate_init;
int (* (*_298)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned char*, unsigned long long*) = &::OSSL_FUNC_kem_encapsulate;
int (* (*_299)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_decapsulate_init;
int (* (*_300)(const struct ossl_dispatch_st*))(void*, void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_auth_decapsulate_init;
int (* (*_301)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_kem_decapsulate;
void (* (*_302)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kem_freectx;
void* (* (*_303)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kem_dupctx;
int (* (*_304)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_get_ctx_params;
const struct ossl_param_st* (* (*_305)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_kem_gettable_ctx_params;
int (* (*_306)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_set_ctx_params;
const struct ossl_param_st* (* (*_307)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_kem_settable_ctx_params;
void* (* (*_308)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_encoder_newctx;
void (* (*_309)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_encoder_freectx;
int (* (*_310)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_encoder_get_params;
const struct ossl_param_st* (* (*_311)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_encoder_gettable_params;
int (* (*_312)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_encoder_set_ctx_params;
const struct ossl_param_st* (* (*_313)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_encoder_settable_ctx_params;
int (* (*_314)(const struct ossl_dispatch_st*))(void*, int) = &::OSSL_FUNC_encoder_does_selection;
int (* (*_315)(const struct ossl_dispatch_st*))(void*, struct ossl_core_bio_st*, const void*, struct ossl_param_st[], int, int (*)(char*, unsigned long long, unsigned long long*, struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_encoder_encode;
void* (* (*_316)(const struct ossl_dispatch_st*))(void*, int, struct ossl_param_st[]) = &::OSSL_FUNC_encoder_import_object;
void (* (*_317)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_encoder_free_object;
void* (* (*_318)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_decoder_newctx;
void (* (*_319)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_decoder_freectx;
int (* (*_320)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_decoder_get_params;
const struct ossl_param_st* (* (*_321)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_decoder_gettable_params;
int (* (*_322)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_decoder_set_ctx_params;
const struct ossl_param_st* (* (*_323)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_decoder_settable_ctx_params;
int (* (*_324)(const struct ossl_dispatch_st*))(void*, int) = &::OSSL_FUNC_decoder_does_selection;
int (* (*_325)(const struct ossl_dispatch_st*))(void*, struct ossl_core_bio_st*, int, int (*)(struct ossl_param_st[], void*), void*, int (*)(char*, unsigned long long, unsigned long long*, struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_decoder_decode;
int (* (*_326)(const struct ossl_dispatch_st*))(void*, const void*, unsigned long long, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_decoder_export_object;
void* (* (*_327)(const struct ossl_dispatch_st*))(void*, const char*) = &::OSSL_FUNC_store_open;
void* (* (*_328)(const struct ossl_dispatch_st*))(void*, struct ossl_core_bio_st*) = &::OSSL_FUNC_store_attach;
const struct ossl_param_st* (* (*_329)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_store_settable_ctx_params;
int (* (*_330)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_store_set_ctx_params;
int (* (*_331)(const struct ossl_dispatch_st*))(void*, int (*)(struct ossl_param_st[], void*), void*, int (*)(char*, unsigned long long, unsigned long long*, struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_store_load;
int (* (*_332)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_store_eof;
int (* (*_333)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_store_close;
int (* (*_334)(const struct ossl_dispatch_st*))(void*, const void*, unsigned long long, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_store_export_object;
int (* (*_335)(const struct ossl_dispatch_st*))(void*, const char*, struct ossl_param_st[], int (*)(char*, unsigned long long, unsigned long long*, struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_store_delete;
void* (* (*_336)(const struct ossl_dispatch_st*))(void*, const char*, struct ossl_param_st[], int (*)(char*, unsigned long long, unsigned long long*, struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_store_open_ex;
EVP_CTRL_TLS1_1_MULTIBLOCK_PARAM& (EVP_CTRL_TLS1_1_MULTIBLOCK_PARAM::*_337)(EVP_CTRL_TLS1_1_MULTIBLOCK_PARAM&&) = &EVP_CTRL_TLS1_1_MULTIBLOCK_PARAM::operator=;
struct evp_cipher_info_st& (evp_cipher_info_st::*_338)(struct evp_cipher_info_st&&) = &evp_cipher_info_st::operator=;
struct asn1_string_st& (asn1_string_st::*_339)(struct asn1_string_st&&) = &asn1_string_st::operator=;
struct ASN1_ENCODING_st& (ASN1_ENCODING_st::*_340)(struct ASN1_ENCODING_st&&) = &ASN1_ENCODING_st::operator=;
struct asn1_string_table_st& (asn1_string_table_st::*_341)(struct asn1_string_table_st&&) = &asn1_string_table_st::operator=;
struct asn1_type_st& (asn1_type_st::*_342)(struct asn1_type_st&&) = &asn1_type_st::operator=;
struct BIT_STRING_BITNAME_st& (BIT_STRING_BITNAME_st::*_343)(struct BIT_STRING_BITNAME_st&&) = &BIT_STRING_BITNAME_st::operator=;
struct X509_algor_st* (*_344)(struct X509_algor_st*) = &::ossl_check_X509_ALGOR_type;
const struct stack_st* (*_345)(const struct stack_st_X509_ALGOR*) = &::ossl_check_const_X509_ALGOR_sk_type;
struct stack_st* (*_346)(struct stack_st_X509_ALGOR*) = &::ossl_check_X509_ALGOR_sk_type;
int (* (*_347)(int (*)(const struct X509_algor_st* const*, const struct X509_algor_st* const*)))(const void*, const void*) = &::ossl_check_X509_ALGOR_compfunc_type;
void* (* (*_348)(struct X509_algor_st* (*)(const struct X509_algor_st*)))(const void*) = &::ossl_check_X509_ALGOR_copyfunc_type;
void (* (*_349)(void (*)(struct X509_algor_st*)))(void*) = &::ossl_check_X509_ALGOR_freefunc_type;
struct asn1_string_table_st* (*_350)(struct asn1_string_table_st*) = &::ossl_check_ASN1_STRING_TABLE_type;
const struct stack_st* (*_351)(const struct stack_st_ASN1_STRING_TABLE*) = &::ossl_check_const_ASN1_STRING_TABLE_sk_type;
struct stack_st* (*_352)(struct stack_st_ASN1_STRING_TABLE*) = &::ossl_check_ASN1_STRING_TABLE_sk_type;
int (* (*_353)(int (*)(const struct asn1_string_table_st* const*, const struct asn1_string_table_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_STRING_TABLE_compfunc_type;
void* (* (*_354)(struct asn1_string_table_st* (*)(const struct asn1_string_table_st*)))(const void*) = &::ossl_check_ASN1_STRING_TABLE_copyfunc_type;
void (* (*_355)(void (*)(struct asn1_string_table_st*)))(void*) = &::ossl_check_ASN1_STRING_TABLE_freefunc_type;
struct asn1_type_st* (*_356)(struct asn1_type_st*) = &::ossl_check_ASN1_TYPE_type;
const struct stack_st* (*_357)(const struct stack_st_ASN1_TYPE*) = &::ossl_check_const_ASN1_TYPE_sk_type;
struct stack_st* (*_358)(struct stack_st_ASN1_TYPE*) = &::ossl_check_ASN1_TYPE_sk_type;
int (* (*_359)(int (*)(const struct asn1_type_st* const*, const struct asn1_type_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_TYPE_compfunc_type;
void* (* (*_360)(struct asn1_type_st* (*)(const struct asn1_type_st*)))(const void*) = &::ossl_check_ASN1_TYPE_copyfunc_type;
void (* (*_361)(void (*)(struct asn1_type_st*)))(void*) = &::ossl_check_ASN1_TYPE_freefunc_type;
struct asn1_object_st* (*_362)(struct asn1_object_st*) = &::ossl_check_ASN1_OBJECT_type;
const struct stack_st* (*_363)(const struct stack_st_ASN1_OBJECT*) = &::ossl_check_const_ASN1_OBJECT_sk_type;
struct stack_st* (*_364)(struct stack_st_ASN1_OBJECT*) = &::ossl_check_ASN1_OBJECT_sk_type;
int (* (*_365)(int (*)(const struct asn1_object_st* const*, const struct asn1_object_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_OBJECT_compfunc_type;
void* (* (*_366)(struct asn1_object_st* (*)(const struct asn1_object_st*)))(const void*) = &::ossl_check_ASN1_OBJECT_copyfunc_type;
void (* (*_367)(void (*)(struct asn1_object_st*)))(void*) = &::ossl_check_ASN1_OBJECT_freefunc_type;
struct asn1_string_st* (*_368)(struct asn1_string_st*) = &::ossl_check_ASN1_INTEGER_type;
const struct stack_st* (*_369)(const struct stack_st_ASN1_INTEGER*) = &::ossl_check_const_ASN1_INTEGER_sk_type;
struct stack_st* (*_370)(struct stack_st_ASN1_INTEGER*) = &::ossl_check_ASN1_INTEGER_sk_type;
int (* (*_371)(int (*)(const struct asn1_string_st* const*, const struct asn1_string_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_INTEGER_compfunc_type;
void* (* (*_372)(struct asn1_string_st* (*)(const struct asn1_string_st*)))(const void*) = &::ossl_check_ASN1_INTEGER_copyfunc_type;
void (* (*_373)(void (*)(struct asn1_string_st*)))(void*) = &::ossl_check_ASN1_INTEGER_freefunc_type;
struct asn1_string_st* (*_374)(struct asn1_string_st*) = &::ossl_check_ASN1_UTF8STRING_type;
const struct stack_st* (*_375)(const struct stack_st_ASN1_UTF8STRING*) = &::ossl_check_const_ASN1_UTF8STRING_sk_type;
struct stack_st* (*_376)(struct stack_st_ASN1_UTF8STRING*) = &::ossl_check_ASN1_UTF8STRING_sk_type;
int (* (*_377)(int (*)(const struct asn1_string_st* const*, const struct asn1_string_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_UTF8STRING_compfunc_type;
void* (* (*_378)(struct asn1_string_st* (*)(const struct asn1_string_st*)))(const void*) = &::ossl_check_ASN1_UTF8STRING_copyfunc_type;
void (* (*_379)(void (*)(struct asn1_string_st*)))(void*) = &::ossl_check_ASN1_UTF8STRING_freefunc_type;
struct asn1_string_st* (*_380)(struct asn1_string_st*) = &::ossl_check_ASN1_GENERALSTRING_type;
const struct stack_st* (*_381)(const struct stack_st_ASN1_GENERALSTRING*) = &::ossl_check_const_ASN1_GENERALSTRING_sk_type;
struct stack_st* (*_382)(struct stack_st_ASN1_GENERALSTRING*) = &::ossl_check_ASN1_GENERALSTRING_sk_type;
int (* (*_383)(int (*)(const struct asn1_string_st* const*, const struct asn1_string_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_GENERALSTRING_compfunc_type;
void* (* (*_384)(struct asn1_string_st* (*)(const struct asn1_string_st*)))(const void*) = &::ossl_check_ASN1_GENERALSTRING_copyfunc_type;
void (* (*_385)(void (*)(struct asn1_string_st*)))(void*) = &::ossl_check_ASN1_GENERALSTRING_freefunc_type;
struct obj_name_st& (obj_name_st::*_386)(struct obj_name_st&&) = &obj_name_st::operator=;
EC_builtin_curve& (EC_builtin_curve::*_387)(EC_builtin_curve&&) = &EC_builtin_curve::operator=;
struct rsa_pss_params_st& (rsa_pss_params_st::*_388)(struct rsa_pss_params_st&&) = &rsa_pss_params_st::operator=;
struct rsa_oaep_params_st& (rsa_oaep_params_st::*_389)(struct rsa_oaep_params_st&&) = &rsa_oaep_params_st::operator=;
struct SHAstate_st& (SHAstate_st::*_390)(struct SHAstate_st&&) = &SHAstate_st::operator=;
struct SHA256state_st& (SHA256state_st::*_391)(struct SHA256state_st&&) = &SHA256state_st::operator=;
struct SHA512state_st& (SHA512state_st::*_392)(struct SHA512state_st&&) = &SHA512state_st::operator=;
struct X509_algor_st& (X509_algor_st::*_393)(struct X509_algor_st&&) = &X509_algor_st::operator=;
struct X509_val_st& (X509_val_st::*_394)(struct X509_val_st&&) = &X509_val_st::operator=;
struct private_key_st& (private_key_st::*_395)(struct private_key_st&&) = &private_key_st::operator=;
struct X509_info_st& (X509_info_st::*_396)(struct X509_info_st&&) = &X509_info_st::operator=;
struct Netscape_spkac_st& (Netscape_spkac_st::*_397)(struct Netscape_spkac_st&&) = &Netscape_spkac_st::operator=;
struct Netscape_spki_st& (Netscape_spki_st::*_398)(struct Netscape_spki_st&&) = &Netscape_spki_st::operator=;
struct Netscape_certificate_sequence& (Netscape_certificate_sequence::*_399)(struct Netscape_certificate_sequence&&) = &Netscape_certificate_sequence::operator=;
struct PBEPARAM_st& (PBEPARAM_st::*_400)(struct PBEPARAM_st&&) = &PBEPARAM_st::operator=;
struct PBE2PARAM_st& (PBE2PARAM_st::*_401)(struct PBE2PARAM_st&&) = &PBE2PARAM_st::operator=;
struct PBKDF2PARAM_st& (PBKDF2PARAM_st::*_402)(struct PBKDF2PARAM_st&&) = &PBKDF2PARAM_st::operator=;
PBMAC1PARAM& (PBMAC1PARAM::*_403)(PBMAC1PARAM&&) = &PBMAC1PARAM::operator=;
struct SCRYPT_PARAMS_st& (SCRYPT_PARAMS_st::*_404)(struct SCRYPT_PARAMS_st&&) = &SCRYPT_PARAMS_st::operator=;
struct X509_name_st* (*_405)(struct X509_name_st*) = &::ossl_check_X509_NAME_type;
const struct stack_st* (*_406)(const struct stack_st_X509_NAME*) = &::ossl_check_const_X509_NAME_sk_type;
struct stack_st* (*_407)(struct stack_st_X509_NAME*) = &::ossl_check_X509_NAME_sk_type;
int (* (*_408)(int (*)(const struct X509_name_st* const*, const struct X509_name_st* const*)))(const void*, const void*) = &::ossl_check_X509_NAME_compfunc_type;
void* (* (*_409)(struct X509_name_st* (*)(const struct X509_name_st*)))(const void*) = &::ossl_check_X509_NAME_copyfunc_type;
void (* (*_410)(void (*)(struct X509_name_st*)))(void*) = &::ossl_check_X509_NAME_freefunc_type;
struct x509_st* (*_411)(struct x509_st*) = &::ossl_check_X509_type;
const struct stack_st* (*_412)(const struct stack_st_X509*) = &::ossl_check_const_X509_sk_type;
struct stack_st* (*_413)(struct stack_st_X509*) = &::ossl_check_X509_sk_type;
int (* (*_414)(int (*)(const struct x509_st* const*, const struct x509_st* const*)))(const void*, const void*) = &::ossl_check_X509_compfunc_type;
void* (* (*_415)(struct x509_st* (*)(const struct x509_st*)))(const void*) = &::ossl_check_X509_copyfunc_type;
void (* (*_416)(void (*)(struct x509_st*)))(void*) = &::ossl_check_X509_freefunc_type;
struct x509_revoked_st* (*_417)(struct x509_revoked_st*) = &::ossl_check_X509_REVOKED_type;
const struct stack_st* (*_418)(const struct stack_st_X509_REVOKED*) = &::ossl_check_const_X509_REVOKED_sk_type;
struct stack_st* (*_419)(struct stack_st_X509_REVOKED*) = &::ossl_check_X509_REVOKED_sk_type;
int (* (*_420)(int (*)(const struct x509_revoked_st* const*, const struct x509_revoked_st* const*)))(const void*, const void*) = &::ossl_check_X509_REVOKED_compfunc_type;
void* (* (*_421)(struct x509_revoked_st* (*)(const struct x509_revoked_st*)))(const void*) = &::ossl_check_X509_REVOKED_copyfunc_type;
void (* (*_422)(void (*)(struct x509_revoked_st*)))(void*) = &::ossl_check_X509_REVOKED_freefunc_type;
struct X509_crl_st* (*_423)(struct X509_crl_st*) = &::ossl_check_X509_CRL_type;
const struct stack_st* (*_424)(const struct stack_st_X509_CRL*) = &::ossl_check_const_X509_CRL_sk_type;
struct stack_st* (*_425)(struct stack_st_X509_CRL*) = &::ossl_check_X509_CRL_sk_type;
int (* (*_426)(int (*)(const struct X509_crl_st* const*, const struct X509_crl_st* const*)))(const void*, const void*) = &::ossl_check_X509_CRL_compfunc_type;
void* (* (*_427)(struct X509_crl_st* (*)(const struct X509_crl_st*)))(const void*) = &::ossl_check_X509_CRL_copyfunc_type;
void (* (*_428)(void (*)(struct X509_crl_st*)))(void*) = &::ossl_check_X509_CRL_freefunc_type;
struct X509_name_entry_st* (*_429)(struct X509_name_entry_st*) = &::ossl_check_X509_NAME_ENTRY_type;
const struct stack_st* (*_430)(const struct stack_st_X509_NAME_ENTRY*) = &::ossl_check_const_X509_NAME_ENTRY_sk_type;
struct stack_st* (*_431)(struct stack_st_X509_NAME_ENTRY*) = &::ossl_check_X509_NAME_ENTRY_sk_type;
int (* (*_432)(int (*)(const struct X509_name_entry_st* const*, const struct X509_name_entry_st* const*)))(const void*, const void*) = &::ossl_check_X509_NAME_ENTRY_compfunc_type;
void* (* (*_433)(struct X509_name_entry_st* (*)(const struct X509_name_entry_st*)))(const void*) = &::ossl_check_X509_NAME_ENTRY_copyfunc_type;
void (* (*_434)(void (*)(struct X509_name_entry_st*)))(void*) = &::ossl_check_X509_NAME_ENTRY_freefunc_type;
struct X509_extension_st* (*_435)(struct X509_extension_st*) = &::ossl_check_X509_EXTENSION_type;
const struct stack_st* (*_436)(const struct stack_st_X509_EXTENSION*) = &::ossl_check_const_X509_EXTENSION_sk_type;
struct stack_st* (*_437)(struct stack_st_X509_EXTENSION*) = &::ossl_check_X509_EXTENSION_sk_type;
int (* (*_438)(int (*)(const struct X509_extension_st* const*, const struct X509_extension_st* const*)))(const void*, const void*) = &::ossl_check_X509_EXTENSION_compfunc_type;
void* (* (*_439)(struct X509_extension_st* (*)(const struct X509_extension_st*)))(const void*) = &::ossl_check_X509_EXTENSION_copyfunc_type;
void (* (*_440)(void (*)(struct X509_extension_st*)))(void*) = &::ossl_check_X509_EXTENSION_freefunc_type;
struct x509_attributes_st* (*_441)(struct x509_attributes_st*) = &::ossl_check_X509_ATTRIBUTE_type;
const struct stack_st* (*_442)(const struct stack_st_X509_ATTRIBUTE*) = &::ossl_check_const_X509_ATTRIBUTE_sk_type;
struct stack_st* (*_443)(struct stack_st_X509_ATTRIBUTE*) = &::ossl_check_X509_ATTRIBUTE_sk_type;
int (* (*_444)(int (*)(const struct x509_attributes_st* const*, const struct x509_attributes_st* const*)))(const void*, const void*) = &::ossl_check_X509_ATTRIBUTE_compfunc_type;
void* (* (*_445)(struct x509_attributes_st* (*)(const struct x509_attributes_st*)))(const void*) = &::ossl_check_X509_ATTRIBUTE_copyfunc_type;
void (* (*_446)(void (*)(struct x509_attributes_st*)))(void*) = &::ossl_check_X509_ATTRIBUTE_freefunc_type;
struct X509_info_st* (*_447)(struct X509_info_st*) = &::ossl_check_X509_INFO_type;
const struct stack_st* (*_448)(const struct stack_st_X509_INFO*) = &::ossl_check_const_X509_INFO_sk_type;
struct stack_st* (*_449)(struct stack_st_X509_INFO*) = &::ossl_check_X509_INFO_sk_type;
int (* (*_450)(int (*)(const struct X509_info_st* const*, const struct X509_info_st* const*)))(const void*, const void*) = &::ossl_check_X509_INFO_compfunc_type;
void* (* (*_451)(struct X509_info_st* (*)(const struct X509_info_st*)))(const void*) = &::ossl_check_X509_INFO_copyfunc_type;
void (* (*_452)(void (*)(struct X509_info_st*)))(void*) = &::ossl_check_X509_INFO_freefunc_type;
struct x509_trust_st& (x509_trust_st::*_453)(struct x509_trust_st&&) = &x509_trust_st::operator=;
struct x509_lookup_st* (*_454)(struct x509_lookup_st*) = &::ossl_check_X509_LOOKUP_type;
const struct stack_st* (*_455)(const struct stack_st_X509_LOOKUP*) = &::ossl_check_const_X509_LOOKUP_sk_type;
struct stack_st* (*_456)(struct stack_st_X509_LOOKUP*) = &::ossl_check_X509_LOOKUP_sk_type;
int (* (*_457)(int (*)(const struct x509_lookup_st* const*, const struct x509_lookup_st* const*)))(const void*, const void*) = &::ossl_check_X509_LOOKUP_compfunc_type;
void* (* (*_458)(struct x509_lookup_st* (*)(const struct x509_lookup_st*)))(const void*) = &::ossl_check_X509_LOOKUP_copyfunc_type;
void (* (*_459)(void (*)(struct x509_lookup_st*)))(void*) = &::ossl_check_X509_LOOKUP_freefunc_type;
struct x509_object_st* (*_460)(struct x509_object_st*) = &::ossl_check_X509_OBJECT_type;
const struct stack_st* (*_461)(const struct stack_st_X509_OBJECT*) = &::ossl_check_const_X509_OBJECT_sk_type;
struct stack_st* (*_462)(struct stack_st_X509_OBJECT*) = &::ossl_check_X509_OBJECT_sk_type;
int (* (*_463)(int (*)(const struct x509_object_st* const*, const struct x509_object_st* const*)))(const void*, const void*) = &::ossl_check_X509_OBJECT_compfunc_type;
void* (* (*_464)(struct x509_object_st* (*)(const struct x509_object_st*)))(const void*) = &::ossl_check_X509_OBJECT_copyfunc_type;
void (* (*_465)(void (*)(struct x509_object_st*)))(void*) = &::ossl_check_X509_OBJECT_freefunc_type;
struct X509_VERIFY_PARAM_st* (*_466)(struct X509_VERIFY_PARAM_st*) = &::ossl_check_X509_VERIFY_PARAM_type;
const struct stack_st* (*_467)(const struct stack_st_X509_VERIFY_PARAM*) = &::ossl_check_const_X509_VERIFY_PARAM_sk_type;
struct stack_st* (*_468)(struct stack_st_X509_VERIFY_PARAM*) = &::ossl_check_X509_VERIFY_PARAM_sk_type;
int (* (*_469)(int (*)(const struct X509_VERIFY_PARAM_st* const*, const struct X509_VERIFY_PARAM_st* const*)))(const void*, const void*) = &::ossl_check_X509_VERIFY_PARAM_compfunc_type;
void* (* (*_470)(struct X509_VERIFY_PARAM_st* (*)(const struct X509_VERIFY_PARAM_st*)))(const void*) = &::ossl_check_X509_VERIFY_PARAM_copyfunc_type;
void (* (*_471)(void (*)(struct X509_VERIFY_PARAM_st*)))(void*) = &::ossl_check_X509_VERIFY_PARAM_freefunc_type;
struct x509_trust_st* (*_472)(struct x509_trust_st*) = &::ossl_check_X509_TRUST_type;
const struct stack_st* (*_473)(const struct stack_st_X509_TRUST*) = &::ossl_check_const_X509_TRUST_sk_type;
struct stack_st* (*_474)(struct stack_st_X509_TRUST*) = &::ossl_check_X509_TRUST_sk_type;
int (* (*_475)(int (*)(const struct x509_trust_st* const*, const struct x509_trust_st* const*)))(const void*, const void*) = &::ossl_check_X509_TRUST_compfunc_type;
void* (* (*_476)(struct x509_trust_st* (*)(const struct x509_trust_st*)))(const void*) = &::ossl_check_X509_TRUST_copyfunc_type;
void (* (*_477)(void (*)(struct x509_trust_st*)))(void*) = &::ossl_check_X509_TRUST_freefunc_type;
union lhash_st_OPENSSL_STRING::lh_OPENSSL_STRING_dummy& (lhash_st_OPENSSL_STRING::lh_OPENSSL_STRING_dummy::*_478)(union lhash_st_OPENSSL_STRING::lh_OPENSSL_STRING_dummy&&) = &lhash_st_OPENSSL_STRING::lh_OPENSSL_STRING_dummy::operator=;
struct lhash_st_OPENSSL_STRING& (lhash_st_OPENSSL_STRING::*_479)(struct lhash_st_OPENSSL_STRING&&) = &lhash_st_OPENSSL_STRING::operator=;
union lhash_st_OPENSSL_CSTRING::lh_OPENSSL_CSTRING_dummy& (lhash_st_OPENSSL_CSTRING::lh_OPENSSL_CSTRING_dummy::*_480)(union lhash_st_OPENSSL_CSTRING::lh_OPENSSL_CSTRING_dummy&&) = &lhash_st_OPENSSL_CSTRING::lh_OPENSSL_CSTRING_dummy::operator=;
struct lhash_st_OPENSSL_CSTRING& (lhash_st_OPENSSL_CSTRING::*_481)(struct lhash_st_OPENSSL_CSTRING&&) = &lhash_st_OPENSSL_CSTRING::operator=;
unsigned long (*_482)(const void*, unsigned long (*)(const void*)) = &::lh_OPENSSL_STRING_hash_thunk;
int (*_483)(const void*, const void*, int (*)(const void*, const void*)) = &::lh_OPENSSL_STRING_comp_thunk;
void (*_484)(void*, void (*)(void*)) = &::lh_OPENSSL_STRING_doall_thunk;
void (*_485)(void*, void*, void (*)(void*, void*)) = &::lh_OPENSSL_STRING_doall_arg_thunk;
char** (*_486)(char**) = &::ossl_check_OPENSSL_STRING_lh_plain_type;
const char** (*_487)(const char**) = &::ossl_check_const_OPENSSL_STRING_lh_plain_type;
const struct lhash_st* (*_488)(const struct lhash_st_OPENSSL_STRING*) = &::ossl_check_const_OPENSSL_STRING_lh_type;
struct lhash_st* (*_489)(struct lhash_st_OPENSSL_STRING*) = &::ossl_check_OPENSSL_STRING_lh_type;
int (* (*_490)(int (*)(const char**, const char**)))(const void*, const void*) = &::ossl_check_OPENSSL_STRING_lh_compfunc_type;
unsigned long (* (*_491)(unsigned long (*)(const char**)))(const void*) = &::ossl_check_OPENSSL_STRING_lh_hashfunc_type;
void (* (*_492)(void (*)(char**)))(void*) = &::ossl_check_OPENSSL_STRING_lh_doallfunc_type;
unsigned long (*_493)(const void*, unsigned long (*)(const void*)) = &::lh_OPENSSL_CSTRING_hash_thunk;
int (*_494)(const void*, const void*, int (*)(const void*, const void*)) = &::lh_OPENSSL_CSTRING_comp_thunk;
void (*_495)(void*, void (*)(void*)) = &::lh_OPENSSL_CSTRING_doall_thunk;
void (*_496)(void*, void*, void (*)(void*, void*)) = &::lh_OPENSSL_CSTRING_doall_arg_thunk;
const char** (*_497)(const char**) = &::ossl_check_OPENSSL_CSTRING_lh_plain_type;
const const char** (*_498)(const const char**) = &::ossl_check_const_OPENSSL_CSTRING_lh_plain_type;
const struct lhash_st* (*_499)(const struct lhash_st_OPENSSL_CSTRING*) = &::ossl_check_const_OPENSSL_CSTRING_lh_type;
struct lhash_st* (*_500)(struct lhash_st_OPENSSL_CSTRING*) = &::ossl_check_OPENSSL_CSTRING_lh_type;
int (* (*_501)(int (*)(const const char**, const const char**)))(const void*, const void*) = &::ossl_check_OPENSSL_CSTRING_lh_compfunc_type;
unsigned long (* (*_502)(unsigned long (*)(const const char**)))(const void*) = &::ossl_check_OPENSSL_CSTRING_lh_hashfunc_type;
void (* (*_503)(void (*)(const char**)))(void*) = &::ossl_check_OPENSSL_CSTRING_lh_doallfunc_type;
struct PKCS7_CTX_st& (PKCS7_CTX_st::*_504)(struct PKCS7_CTX_st&&) = &PKCS7_CTX_st::operator=;
struct pkcs7_issuer_and_serial_st& (pkcs7_issuer_and_serial_st::*_505)(struct pkcs7_issuer_and_serial_st&&) = &pkcs7_issuer_and_serial_st::operator=;
struct pkcs7_signer_info_st& (pkcs7_signer_info_st::*_506)(struct pkcs7_signer_info_st&&) = &pkcs7_signer_info_st::operator=;
struct pkcs7_recip_info_st& (pkcs7_recip_info_st::*_507)(struct pkcs7_recip_info_st&&) = &pkcs7_recip_info_st::operator=;
struct pkcs7_signed_st& (pkcs7_signed_st::*_508)(struct pkcs7_signed_st&&) = &pkcs7_signed_st::operator=;
struct pkcs7_enc_content_st& (pkcs7_enc_content_st::*_509)(struct pkcs7_enc_content_st&&) = &pkcs7_enc_content_st::operator=;
struct pkcs7_enveloped_st& (pkcs7_enveloped_st::*_510)(struct pkcs7_enveloped_st&&) = &pkcs7_enveloped_st::operator=;
struct pkcs7_signedandenveloped_st& (pkcs7_signedandenveloped_st::*_511)(struct pkcs7_signedandenveloped_st&&) = &pkcs7_signedandenveloped_st::operator=;
struct pkcs7_digest_st& (pkcs7_digest_st::*_512)(struct pkcs7_digest_st&&) = &pkcs7_digest_st::operator=;
struct pkcs7_encrypted_st& (pkcs7_encrypted_st::*_513)(struct pkcs7_encrypted_st&&) = &pkcs7_encrypted_st::operator=;
struct pkcs7_st& (pkcs7_st::*_514)(struct pkcs7_st&&) = &pkcs7_st::operator=;
struct pkcs7_signer_info_st* (*_515)(struct pkcs7_signer_info_st*) = &::ossl_check_PKCS7_SIGNER_INFO_type;
const struct stack_st* (*_516)(const struct stack_st_PKCS7_SIGNER_INFO*) = &::ossl_check_const_PKCS7_SIGNER_INFO_sk_type;
struct stack_st* (*_517)(struct stack_st_PKCS7_SIGNER_INFO*) = &::ossl_check_PKCS7_SIGNER_INFO_sk_type;
int (* (*_518)(int (*)(const struct pkcs7_signer_info_st* const*, const struct pkcs7_signer_info_st* const*)))(const void*, const void*) = &::ossl_check_PKCS7_SIGNER_INFO_compfunc_type;
void* (* (*_519)(struct pkcs7_signer_info_st* (*)(const struct pkcs7_signer_info_st*)))(const void*) = &::ossl_check_PKCS7_SIGNER_INFO_copyfunc_type;
void (* (*_520)(void (*)(struct pkcs7_signer_info_st*)))(void*) = &::ossl_check_PKCS7_SIGNER_INFO_freefunc_type;
struct pkcs7_recip_info_st* (*_521)(struct pkcs7_recip_info_st*) = &::ossl_check_PKCS7_RECIP_INFO_type;
const struct stack_st* (*_522)(const struct stack_st_PKCS7_RECIP_INFO*) = &::ossl_check_const_PKCS7_RECIP_INFO_sk_type;
struct stack_st* (*_523)(struct stack_st_PKCS7_RECIP_INFO*) = &::ossl_check_PKCS7_RECIP_INFO_sk_type;
int (* (*_524)(int (*)(const struct pkcs7_recip_info_st* const*, const struct pkcs7_recip_info_st* const*)))(const void*, const void*) = &::ossl_check_PKCS7_RECIP_INFO_compfunc_type;
void* (* (*_525)(struct pkcs7_recip_info_st* (*)(const struct pkcs7_recip_info_st*)))(const void*) = &::ossl_check_PKCS7_RECIP_INFO_copyfunc_type;
void (* (*_526)(void (*)(struct pkcs7_recip_info_st*)))(void*) = &::ossl_check_PKCS7_RECIP_INFO_freefunc_type;
struct pkcs7_st* (*_527)(struct pkcs7_st*) = &::ossl_check_PKCS7_type;
const struct stack_st* (*_528)(const struct stack_st_PKCS7*) = &::ossl_check_const_PKCS7_sk_type;
struct stack_st* (*_529)(struct stack_st_PKCS7*) = &::ossl_check_PKCS7_sk_type;
int (* (*_530)(int (*)(const struct pkcs7_st* const*, const struct pkcs7_st* const*)))(const void*, const void*) = &::ossl_check_PKCS7_compfunc_type;
void* (* (*_531)(struct pkcs7_st* (*)(const struct pkcs7_st*)))(const void*) = &::ossl_check_PKCS7_copyfunc_type;
void (* (*_532)(void (*)(struct pkcs7_st*)))(void*) = &::ossl_check_PKCS7_freefunc_type;
CONF_VALUE& (CONF_VALUE::*_533)(CONF_VALUE&&) = &CONF_VALUE::operator=;
union lhash_st_CONF_VALUE::lh_CONF_VALUE_dummy& (lhash_st_CONF_VALUE::lh_CONF_VALUE_dummy::*_534)(union lhash_st_CONF_VALUE::lh_CONF_VALUE_dummy&&) = &lhash_st_CONF_VALUE::lh_CONF_VALUE_dummy::operator=;
struct lhash_st_CONF_VALUE& (lhash_st_CONF_VALUE::*_535)(struct lhash_st_CONF_VALUE&&) = &lhash_st_CONF_VALUE::operator=;
struct conf_method_st& (conf_method_st::*_536)(struct conf_method_st&&) = &conf_method_st::operator=;
struct conf_st& (conf_st::*_537)(struct conf_st&&) = &conf_st::operator=;
CONF_VALUE* (*_538)(CONF_VALUE*) = &::ossl_check_CONF_VALUE_type;
const struct stack_st* (*_539)(const struct stack_st_CONF_VALUE*) = &::ossl_check_const_CONF_VALUE_sk_type;
struct stack_st* (*_540)(struct stack_st_CONF_VALUE*) = &::ossl_check_CONF_VALUE_sk_type;
int (* (*_541)(int (*)(const CONF_VALUE* const*, const CONF_VALUE* const*)))(const void*, const void*) = &::ossl_check_CONF_VALUE_compfunc_type;
void* (* (*_542)(CONF_VALUE* (*)(const CONF_VALUE*)))(const void*) = &::ossl_check_CONF_VALUE_copyfunc_type;
void (* (*_543)(void (*)(CONF_VALUE*)))(void*) = &::ossl_check_CONF_VALUE_freefunc_type;
unsigned long (*_544)(const void*, unsigned long (*)(const void*)) = &::lh_CONF_VALUE_hash_thunk;
int (*_545)(const void*, const void*, int (*)(const void*, const void*)) = &::lh_CONF_VALUE_comp_thunk;
void (*_546)(void*, void (*)(void*)) = &::lh_CONF_VALUE_doall_thunk;
void (*_547)(void*, void*, void (*)(void*, void*)) = &::lh_CONF_VALUE_doall_arg_thunk;
CONF_VALUE* (*_548)(CONF_VALUE*) = &::ossl_check_CONF_VALUE_lh_plain_type;
const CONF_VALUE* (*_549)(const CONF_VALUE*) = &::ossl_check_const_CONF_VALUE_lh_plain_type;
const struct lhash_st* (*_550)(const struct lhash_st_CONF_VALUE*) = &::ossl_check_const_CONF_VALUE_lh_type;
struct lhash_st* (*_551)(struct lhash_st_CONF_VALUE*) = &::ossl_check_CONF_VALUE_lh_type;
int (* (*_552)(int (*)(const CONF_VALUE*, const CONF_VALUE*)))(const void*, const void*) = &::ossl_check_CONF_VALUE_lh_compfunc_type;
unsigned long (* (*_553)(unsigned long (*)(const CONF_VALUE*)))(const void*) = &::ossl_check_CONF_VALUE_lh_hashfunc_type;
void (* (*_554)(void (*)(CONF_VALUE*)))(void*) = &::ossl_check_CONF_VALUE_lh_doallfunc_type;
struct sct_st* (*_555)(struct sct_st*) = &::ossl_check_SCT_type;
const struct stack_st* (*_556)(const struct stack_st_SCT*) = &::ossl_check_const_SCT_sk_type;
struct stack_st* (*_557)(struct stack_st_SCT*) = &::ossl_check_SCT_sk_type;
int (* (*_558)(int (*)(const struct sct_st* const*, const struct sct_st* const*)))(const void*, const void*) = &::ossl_check_SCT_compfunc_type;
void* (* (*_559)(struct sct_st* (*)(const struct sct_st*)))(const void*) = &::ossl_check_SCT_copyfunc_type;
void (* (*_560)(void (*)(struct sct_st*)))(void*) = &::ossl_check_SCT_freefunc_type;
struct ctlog_st* (*_561)(struct ctlog_st*) = &::ossl_check_CTLOG_type;
const struct stack_st* (*_562)(const struct stack_st_CTLOG*) = &::ossl_check_const_CTLOG_sk_type;
struct stack_st* (*_563)(struct stack_st_CTLOG*) = &::ossl_check_CTLOG_sk_type;
int (* (*_564)(int (*)(const struct ctlog_st* const*, const struct ctlog_st* const*)))(const void*, const void*) = &::ossl_check_CTLOG_compfunc_type;
void* (* (*_565)(struct ctlog_st* (*)(const struct ctlog_st*)))(const void*) = &::ossl_check_CTLOG_copyfunc_type;
void (* (*_566)(void (*)(struct ctlog_st*)))(void*) = &::ossl_check_CTLOG_freefunc_type;
struct tls_session_ticket_ext_st& (tls_session_ticket_ext_st::*_567)(struct tls_session_ticket_ext_st&&) = &tls_session_ticket_ext_st::operator=;
struct err_state_st& (err_state_st::*_568)(struct err_state_st&&) = &err_state_st::operator=;
struct ERR_string_data_st& (ERR_string_data_st::*_569)(struct ERR_string_data_st&&) = &ERR_string_data_st::operator=;
union lhash_st_ERR_STRING_DATA::lh_ERR_STRING_DATA_dummy& (lhash_st_ERR_STRING_DATA::lh_ERR_STRING_DATA_dummy::*_570)(union lhash_st_ERR_STRING_DATA::lh_ERR_STRING_DATA_dummy&&) = &lhash_st_ERR_STRING_DATA::lh_ERR_STRING_DATA_dummy::operator=;
struct lhash_st_ERR_STRING_DATA& (lhash_st_ERR_STRING_DATA::*_571)(struct lhash_st_ERR_STRING_DATA&&) = &lhash_st_ERR_STRING_DATA::operator=;
int (*_572)(unsigned long) = &::ERR_GET_LIB;
int (*_573)(unsigned long) = &::ERR_GET_RFLAGS;
int (*_574)(unsigned long) = &::ERR_GET_REASON;
int (*_575)(unsigned long) = &::ERR_FATAL_ERROR;
int (*_576)(unsigned long) = &::ERR_COMMON_ERROR;
unsigned long (*_577)(const void*, unsigned long (*)(const void*)) = &::lh_ERR_STRING_DATA_hash_thunk;
int (*_578)(const void*, const void*, int (*)(const void*, const void*)) = &::lh_ERR_STRING_DATA_comp_thunk;
void (*_579)(void*, void (*)(void*)) = &::lh_ERR_STRING_DATA_doall_thunk;
void (*_580)(void*, void*, void (*)(void*, void*)) = &::lh_ERR_STRING_DATA_doall_arg_thunk;
struct ERR_string_data_st* (*_581)(struct ERR_string_data_st*) = &::ossl_check_ERR_STRING_DATA_lh_plain_type;
const struct ERR_string_data_st* (*_582)(const struct ERR_string_data_st*) = &::ossl_check_const_ERR_STRING_DATA_lh_plain_type;
const struct lhash_st* (*_583)(const struct lhash_st_ERR_STRING_DATA*) = &::ossl_check_const_ERR_STRING_DATA_lh_type;
struct lhash_st* (*_584)(struct lhash_st_ERR_STRING_DATA*) = &::ossl_check_ERR_STRING_DATA_lh_type;
int (* (*_585)(int (*)(const struct ERR_string_data_st*, const struct ERR_string_data_st*)))(const void*, const void*) = &::ossl_check_ERR_STRING_DATA_lh_compfunc_type;
unsigned long (* (*_586)(unsigned long (*)(const struct ERR_string_data_st*)))(const void*) = &::ossl_check_ERR_STRING_DATA_lh_hashfunc_type;
void (* (*_587)(void (*)(struct ERR_string_data_st*)))(void*) = &::ossl_check_ERR_STRING_DATA_lh_doallfunc_type;
