#include <openssl/ssl.h>
#include <openssl/ssl2.h>
#include <openssl/ssl3.h>
#include <new>

struct srtp_protection_profile_st& (srtp_protection_profile_st::*_0)(struct srtp_protection_profile_st&&) = &srtp_protection_profile_st::operator=;
struct ssl_shutdown_ex_args_st& (ssl_shutdown_ex_args_st::*_1)(struct ssl_shutdown_ex_args_st&&) = &ssl_shutdown_ex_args_st::operator=;
struct ssl_stream_reset_args_st& (ssl_stream_reset_args_st::*_2)(struct ssl_stream_reset_args_st&&) = &ssl_stream_reset_args_st::operator=;
struct ssl_conn_close_info_st& (ssl_conn_close_info_st::*_3)(struct ssl_conn_close_info_st&&) = &ssl_conn_close_info_st::operator=;
struct ssl_poll_item_st& (ssl_poll_item_st::*_4)(struct ssl_poll_item_st&&) = &ssl_poll_item_st::operator=;
void (*_5)(void (*)(void*), void*) = &::sk_SRTP_PROTECTION_PROFILE_freefunc_thunk;
struct srtp_protection_profile_st* (*_6)(struct srtp_protection_profile_st*) = &::ossl_check_SRTP_PROTECTION_PROFILE_type;
const struct stack_st* (*_7)(const struct stack_st_SRTP_PROTECTION_PROFILE*) = &::ossl_check_const_SRTP_PROTECTION_PROFILE_sk_type;
struct stack_st* (*_8)(struct stack_st_SRTP_PROTECTION_PROFILE*) = &::ossl_check_SRTP_PROTECTION_PROFILE_sk_type;
int (* (*_9)(int (*)(const struct srtp_protection_profile_st* const*, const struct srtp_protection_profile_st* const*)))(const void*, const void*) = &::ossl_check_SRTP_PROTECTION_PROFILE_compfunc_type;
void* (* (*_10)(struct srtp_protection_profile_st* (*)(const struct srtp_protection_profile_st*)))(const void*) = &::ossl_check_SRTP_PROTECTION_PROFILE_copyfunc_type;
void (* (*_11)(void (*)(struct srtp_protection_profile_st*)))(void*) = &::ossl_check_SRTP_PROTECTION_PROFILE_freefunc_type;
void (*_12)(void (*)(void*), void*) = &::sk_SSL_CIPHER_freefunc_thunk;
const struct ssl_cipher_st* (*_13)(const struct ssl_cipher_st*) = &::ossl_check_SSL_CIPHER_type;
const struct stack_st* (*_14)(const struct stack_st_SSL_CIPHER*) = &::ossl_check_const_SSL_CIPHER_sk_type;
struct stack_st* (*_15)(struct stack_st_SSL_CIPHER*) = &::ossl_check_SSL_CIPHER_sk_type;
int (* (*_16)(int (*)(const struct ssl_cipher_st* const*, const struct ssl_cipher_st* const*)))(const void*, const void*) = &::ossl_check_SSL_CIPHER_compfunc_type;
void* (* (*_17)(struct ssl_cipher_st* (*)(const struct ssl_cipher_st*)))(const void*) = &::ossl_check_SSL_CIPHER_copyfunc_type;
void (* (*_18)(void (*)(struct ssl_cipher_st*)))(void*) = &::ossl_check_SSL_CIPHER_freefunc_type;
struct bio_poll_descriptor_st (*_19)(struct ssl_st*) = &::SSL_as_poll_descriptor;
void (*_20)(void (*)(void*), void*) = &::sk_OPENSSL_STRING_freefunc_thunk;
char* (*_21)(char*) = &::ossl_check_OPENSSL_STRING_type;
const struct stack_st* (*_22)(const struct stack_st_OPENSSL_STRING*) = &::ossl_check_const_OPENSSL_STRING_sk_type;
struct stack_st* (*_23)(struct stack_st_OPENSSL_STRING*) = &::ossl_check_OPENSSL_STRING_sk_type;
int (* (*_24)(int (*)(const char* const*, const char* const*)))(const void*, const void*) = &::ossl_check_OPENSSL_STRING_compfunc_type;
void* (* (*_25)(char* (*)(const char*)))(const void*) = &::ossl_check_OPENSSL_STRING_copyfunc_type;
void (* (*_26)(void (*)(char*)))(void*) = &::ossl_check_OPENSSL_STRING_freefunc_type;
void (*_27)(void (*)(void*), void*) = &::sk_OPENSSL_CSTRING_freefunc_thunk;
const char* (*_28)(const char*) = &::ossl_check_OPENSSL_CSTRING_type;
const struct stack_st* (*_29)(const struct stack_st_OPENSSL_CSTRING*) = &::ossl_check_const_OPENSSL_CSTRING_sk_type;
struct stack_st* (*_30)(struct stack_st_OPENSSL_CSTRING*) = &::ossl_check_OPENSSL_CSTRING_sk_type;
int (* (*_31)(int (*)(const char* const*, const char* const*)))(const void*, const void*) = &::ossl_check_OPENSSL_CSTRING_compfunc_type;
void* (* (*_32)(char* (*)(const char*)))(const void*) = &::ossl_check_OPENSSL_CSTRING_copyfunc_type;
void (* (*_33)(void (*)(char*)))(void*) = &::ossl_check_OPENSSL_CSTRING_freefunc_type;
void (*_34)(void (*)(void*), void*) = &::sk_OPENSSL_BLOCK_freefunc_thunk;
void* (*_35)(void*) = &::ossl_check_OPENSSL_BLOCK_type;
const struct stack_st* (*_36)(const struct stack_st_OPENSSL_BLOCK*) = &::ossl_check_const_OPENSSL_BLOCK_sk_type;
struct stack_st* (*_37)(struct stack_st_OPENSSL_BLOCK*) = &::ossl_check_OPENSSL_BLOCK_sk_type;
int (* (*_38)(int (*)(const void* const*, const void* const*)))(const void*, const void*) = &::ossl_check_OPENSSL_BLOCK_compfunc_type;
void* (* (*_39)(void* (*)(const void*)))(const void*) = &::ossl_check_OPENSSL_BLOCK_copyfunc_type;
void (* (*_40)(void (*)(void*)))(void*) = &::ossl_check_OPENSSL_BLOCK_freefunc_type;
struct ossl_dispatch_st& (ossl_dispatch_st::*_41)(struct ossl_dispatch_st&&) = &ossl_dispatch_st::operator=;
struct ossl_item_st& (ossl_item_st::*_42)(struct ossl_item_st&&) = &ossl_item_st::operator=;
struct ossl_algorithm_st& (ossl_algorithm_st::*_43)(struct ossl_algorithm_st&&) = &ossl_algorithm_st::operator=;
struct ossl_param_st& (ossl_param_st::*_44)(struct ossl_param_st&&) = &ossl_param_st::operator=;
CRYPTO_dynlock& (CRYPTO_dynlock::*_45)(CRYPTO_dynlock&&) = &CRYPTO_dynlock::operator=;
struct crypto_ex_data_st& (crypto_ex_data_st::*_46)(struct crypto_ex_data_st&&) = &crypto_ex_data_st::operator=;
struct crypto_threadid_st& (crypto_threadid_st::*_47)(struct crypto_threadid_st&&) = &crypto_threadid_st::operator=;
void (*_48)(void (*)(void*), void*) = &::sk_void_freefunc_thunk;
void* (*_49)(void*) = &::ossl_check_void_type;
const struct stack_st* (*_50)(const struct stack_st_void*) = &::ossl_check_const_void_sk_type;
struct stack_st* (*_51)(struct stack_st_void*) = &::ossl_check_void_sk_type;
int (* (*_52)(int (*)(const void* const*, const void* const*)))(const void*, const void*) = &::ossl_check_void_compfunc_type;
void* (* (*_53)(void* (*)(const void*)))(const void*) = &::ossl_check_void_copyfunc_type;
void (* (*_54)(void (*)(void*)))(void*) = &::ossl_check_void_freefunc_type;
void (*_55)(void (*)(void*), void*) = &::sk_SSL_COMP_freefunc_thunk;
struct ssl_comp_st* (*_56)(struct ssl_comp_st*) = &::ossl_check_SSL_COMP_type;
const struct stack_st* (*_57)(const struct stack_st_SSL_COMP*) = &::ossl_check_const_SSL_COMP_sk_type;
struct stack_st* (*_58)(struct stack_st_SSL_COMP*) = &::ossl_check_SSL_COMP_sk_type;
int (* (*_59)(int (*)(const struct ssl_comp_st* const*, const struct ssl_comp_st* const*)))(const void*, const void*) = &::ossl_check_SSL_COMP_compfunc_type;
void* (* (*_60)(struct ssl_comp_st* (*)(const struct ssl_comp_st*)))(const void*) = &::ossl_check_SSL_COMP_copyfunc_type;
void (* (*_61)(void (*)(struct ssl_comp_st*)))(void*) = &::ossl_check_SSL_COMP_freefunc_type;
struct bio_msg_st& (bio_msg_st::*_62)(struct bio_msg_st&&) = &bio_msg_st::operator=;
struct bio_mmsg_cb_args_st& (bio_mmsg_cb_args_st::*_63)(struct bio_mmsg_cb_args_st&&) = &bio_mmsg_cb_args_st::operator=;
struct bio_poll_descriptor_st& (bio_poll_descriptor_st::*_64)(struct bio_poll_descriptor_st&&) = &bio_poll_descriptor_st::operator=;
union BIO_sock_info_u& (BIO_sock_info_u::*_65)(union BIO_sock_info_u&&) = &BIO_sock_info_u::operator=;
void (*_66)(void (*)(void*), void*) = &::sk_BIO_freefunc_thunk;
struct bio_st* (*_67)(struct bio_st*) = &::ossl_check_BIO_type;
const struct stack_st* (*_68)(const struct stack_st_BIO*) = &::ossl_check_const_BIO_sk_type;
struct stack_st* (*_69)(struct stack_st_BIO*) = &::ossl_check_BIO_sk_type;
int (* (*_70)(int (*)(const struct bio_st* const*, const struct bio_st* const*)))(const void*, const void*) = &::ossl_check_BIO_compfunc_type;
void* (* (*_71)(struct bio_st* (*)(const struct bio_st*)))(const void*) = &::ossl_check_BIO_copyfunc_type;
void (* (*_72)(void (*)(struct bio_st*)))(void*) = &::ossl_check_BIO_freefunc_type;
struct buf_mem_st& (buf_mem_st::*_73)(struct buf_mem_st&&) = &buf_mem_st::operator=;
const struct ossl_param_st* (* (*_74)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_gettable_params;
int (* (*_75)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, struct ossl_param_st[]) = &::OSSL_FUNC_core_get_params;
int (* (*_76)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, void (*)(void*), void*) = &::OSSL_FUNC_core_thread_start;
struct openssl_core_ctx_st* (* (*_77)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_get_libctx;
void (* (*_78)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_new_error;
void (* (*_79)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, const char*, int, const char*) = &::OSSL_FUNC_core_set_error_debug;
int (* (*_80)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_set_error_mark;
int (* (*_81)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_clear_last_error_mark;
int (* (*_82)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_core_pop_error_to_mark;
int (* (*_83)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, const char*, const char*, const char*) = &::OSSL_FUNC_core_obj_add_sigid;
int (* (*_84)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, const char*, const char*, const char*) = &::OSSL_FUNC_core_obj_create;
void* (* (*_85)(const struct ossl_dispatch_st*))(unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_malloc;
void* (* (*_86)(const struct ossl_dispatch_st*))(unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_zalloc;
void (* (*_87)(const struct ossl_dispatch_st*))(void*, const char*, int) = &::OSSL_FUNC_CRYPTO_free;
void (* (*_88)(const struct ossl_dispatch_st*))(void*, unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_clear_free;
void* (* (*_89)(const struct ossl_dispatch_st*))(void*, unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_realloc;
void* (* (*_90)(const struct ossl_dispatch_st*))(void*, unsigned long long, unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_clear_realloc;
void* (* (*_91)(const struct ossl_dispatch_st*))(unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_secure_malloc;
void* (* (*_92)(const struct ossl_dispatch_st*))(unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_secure_zalloc;
void (* (*_93)(const struct ossl_dispatch_st*))(void*, const char*, int) = &::OSSL_FUNC_CRYPTO_secure_free;
void (* (*_94)(const struct ossl_dispatch_st*))(void*, unsigned long long, const char*, int) = &::OSSL_FUNC_CRYPTO_secure_clear_free;
int (* (*_95)(const struct ossl_dispatch_st*))(const void*) = &::OSSL_FUNC_CRYPTO_secure_allocated;
void (* (*_96)(const struct ossl_dispatch_st*))(void*, unsigned long long) = &::OSSL_FUNC_OPENSSL_cleanse;
struct ossl_core_bio_st* (* (*_97)(const struct ossl_dispatch_st*))(const char*, const char*) = &::OSSL_FUNC_BIO_new_file;
struct ossl_core_bio_st* (* (*_98)(const struct ossl_dispatch_st*))(const void*, int) = &::OSSL_FUNC_BIO_new_membuf;
int (* (*_99)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*, void*, unsigned long long, unsigned long long*) = &::OSSL_FUNC_BIO_read_ex;
int (* (*_100)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*, const void*, unsigned long long, unsigned long long*) = &::OSSL_FUNC_BIO_write_ex;
int (* (*_101)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*, char*, int) = &::OSSL_FUNC_BIO_gets;
int (* (*_102)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*, const char*) = &::OSSL_FUNC_BIO_puts;
int (* (*_103)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*) = &::OSSL_FUNC_BIO_up_ref;
int (* (*_104)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*) = &::OSSL_FUNC_BIO_free;
int (* (*_105)(const struct ossl_dispatch_st*))(struct ossl_core_bio_st*, int, long, void*) = &::OSSL_FUNC_BIO_ctrl;
void (* (*_106)(const struct ossl_dispatch_st*))(struct openssl_core_ctx_st*, int (**)(const char*, const char*, struct ossl_param_st[])) = &::OSSL_FUNC_indicator_cb;
void (* (*_107)(const struct ossl_dispatch_st*))(struct openssl_core_ctx_st*, int (**)(struct ossl_param_st[], void*), void**) = &::OSSL_FUNC_self_test_cb;
unsigned long long (* (*_108)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char**, int, unsigned long long, unsigned long long) = &::OSSL_FUNC_get_entropy;
unsigned long long (* (*_109)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char**, int, unsigned long long, unsigned long long) = &::OSSL_FUNC_get_user_entropy;
void (* (*_110)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char*, unsigned long long) = &::OSSL_FUNC_cleanup_entropy;
void (* (*_111)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char*, unsigned long long) = &::OSSL_FUNC_cleanup_user_entropy;
unsigned long long (* (*_112)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char**, unsigned long long, unsigned long long, const void*, unsigned long long) = &::OSSL_FUNC_get_nonce;
unsigned long long (* (*_113)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char**, unsigned long long, unsigned long long, const void*, unsigned long long) = &::OSSL_FUNC_get_user_nonce;
void (* (*_114)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char*, unsigned long long) = &::OSSL_FUNC_cleanup_nonce;
void (* (*_115)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, unsigned char*, unsigned long long) = &::OSSL_FUNC_cleanup_user_nonce;
int (* (*_116)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, int (*)(const struct ossl_core_handle_st*, void*), int (*)(const struct ossl_core_handle_st*, void*), int (*)(const char*, void*), void*) = &::OSSL_FUNC_provider_register_child_cb;
void (* (*_117)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_provider_deregister_child_cb;
const char* (* (*_118)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_provider_name;
void* (* (*_119)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_provider_get0_provider_ctx;
const struct ossl_dispatch_st* (* (*_120)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*) = &::OSSL_FUNC_provider_get0_dispatch;
int (* (*_121)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, int) = &::OSSL_FUNC_provider_up_ref;
int (* (*_122)(const struct ossl_dispatch_st*))(const struct ossl_core_handle_st*, int) = &::OSSL_FUNC_provider_free;
void (* (*_123)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_provider_teardown;
const struct ossl_param_st* (* (*_124)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_provider_gettable_params;
int (* (*_125)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_provider_get_params;
const struct ossl_algorithm_st* (* (*_126)(const struct ossl_dispatch_st*))(void*, int, int*) = &::OSSL_FUNC_provider_query_operation;
void (* (*_127)(const struct ossl_dispatch_st*))(void*, int, const struct ossl_algorithm_st*) = &::OSSL_FUNC_provider_unquery_operation;
const struct ossl_item_st* (* (*_128)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_provider_get_reason_strings;
int (* (*_129)(const struct ossl_dispatch_st*))(void*, const char*, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_provider_get_capabilities;
int (* (*_130)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_provider_self_test;
int (* (*_131)(const struct ossl_dispatch_st*))(void*, int, void*, unsigned long long, unsigned int) = &::OSSL_FUNC_provider_random_bytes;
int (* (*_132)(const struct ossl_dispatch_st*))(struct ssl_st*, const unsigned char*, unsigned long long, unsigned long long*, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_crypto_send;
int (* (*_133)(const struct ossl_dispatch_st*))(struct ssl_st*, const unsigned char**, unsigned long long*, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_crypto_recv_rcd;
int (* (*_134)(const struct ossl_dispatch_st*))(struct ssl_st*, unsigned long long, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_crypto_release_rcd;
int (* (*_135)(const struct ossl_dispatch_st*))(struct ssl_st*, unsigned int, int, const unsigned char*, unsigned long long, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_yield_secret;
int (* (*_136)(const struct ossl_dispatch_st*))(struct ssl_st*, const unsigned char*, unsigned long long, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_got_transport_params;
int (* (*_137)(const struct ossl_dispatch_st*))(struct ssl_st*, unsigned char, void*) = &::OSSL_FUNC_SSL_QUIC_TLS_alert;
void* (* (*_138)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_digest_newctx;
int (* (*_139)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_digest_init;
int (* (*_140)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_digest_update;
int (* (*_141)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_digest_final;
int (* (*_142)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_digest_squeeze;
int (* (*_143)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_digest_digest;
void (* (*_144)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_digest_freectx;
void* (* (*_145)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_digest_dupctx;
void (* (*_146)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_digest_copyctx;
int (* (*_147)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_digest_get_params;
int (* (*_148)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_digest_set_ctx_params;
int (* (*_149)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_digest_get_ctx_params;
const struct ossl_param_st* (* (*_150)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_digest_gettable_params;
const struct ossl_param_st* (* (*_151)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_digest_settable_ctx_params;
const struct ossl_param_st* (* (*_152)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_digest_gettable_ctx_params;
void* (* (*_153)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_cipher_newctx;
int (* (*_154)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_encrypt_init;
int (* (*_155)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_decrypt_init;
int (* (*_156)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_cipher_update;
int (* (*_157)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_cipher_final;
int (* (*_158)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_cipher_cipher;
int (* (*_159)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, unsigned long long, const unsigned char**, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_pipeline_encrypt_init;
int (* (*_160)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, unsigned long long, const unsigned char**, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_pipeline_decrypt_init;
int (* (*_161)(const struct ossl_dispatch_st*))(void*, unsigned long long, unsigned char**, unsigned long long*, const unsigned long long*, const unsigned char**, const unsigned long long*) = &::OSSL_FUNC_cipher_pipeline_update;
int (* (*_162)(const struct ossl_dispatch_st*))(void*, unsigned long long, unsigned char**, unsigned long long*, const unsigned long long*) = &::OSSL_FUNC_cipher_pipeline_final;
void (* (*_163)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_cipher_freectx;
void* (* (*_164)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_cipher_dupctx;
int (* (*_165)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_cipher_get_params;
int (* (*_166)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_get_ctx_params;
int (* (*_167)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_set_ctx_params;
const struct ossl_param_st* (* (*_168)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_cipher_gettable_params;
const struct ossl_param_st* (* (*_169)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_cipher_settable_ctx_params;
const struct ossl_param_st* (* (*_170)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_cipher_gettable_ctx_params;
int (* (*_171)(const struct ossl_dispatch_st*))(void*, void*, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_encrypt_skey_init;
int (* (*_172)(const struct ossl_dispatch_st*))(void*, void*, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_cipher_decrypt_skey_init;
void* (* (*_173)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_mac_newctx;
void* (* (*_174)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_mac_dupctx;
void (* (*_175)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_mac_freectx;
int (* (*_176)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_mac_init;
int (* (*_177)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_mac_update;
int (* (*_178)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_mac_final;
const struct ossl_param_st* (* (*_179)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_mac_gettable_params;
const struct ossl_param_st* (* (*_180)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_mac_gettable_ctx_params;
const struct ossl_param_st* (* (*_181)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_mac_settable_ctx_params;
int (* (*_182)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_mac_get_params;
int (* (*_183)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_mac_get_ctx_params;
int (* (*_184)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_mac_set_ctx_params;
int (* (*_185)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_mac_init_skey;
void* (* (*_186)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kdf_newctx;
void* (* (*_187)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kdf_dupctx;
void (* (*_188)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kdf_freectx;
void (* (*_189)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kdf_reset;
int (* (*_190)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_kdf_derive;
const struct ossl_param_st* (* (*_191)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kdf_gettable_params;
const struct ossl_param_st* (* (*_192)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_kdf_gettable_ctx_params;
const struct ossl_param_st* (* (*_193)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_kdf_settable_ctx_params;
int (* (*_194)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_kdf_get_params;
int (* (*_195)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_kdf_get_ctx_params;
int (* (*_196)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_kdf_set_ctx_params;
void* (* (*_197)(const struct ossl_dispatch_st*))(void*, void*, const struct ossl_dispatch_st*) = &::OSSL_FUNC_rand_newctx;
void (* (*_198)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_freectx;
int (* (*_199)(const struct ossl_dispatch_st*))(void*, unsigned int, int, const unsigned char*, unsigned long long, struct ossl_param_st[]) = &::OSSL_FUNC_rand_instantiate;
int (* (*_200)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_uninstantiate;
int (* (*_201)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long, unsigned int, int, const unsigned char*, unsigned long long) = &::OSSL_FUNC_rand_generate;
int (* (*_202)(const struct ossl_dispatch_st*))(void*, int, const unsigned char*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_rand_reseed;
unsigned long long (* (*_203)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned int, unsigned long long, unsigned long long) = &::OSSL_FUNC_rand_nonce;
int (* (*_204)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_enable_locking;
int (* (*_205)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_lock;
void (* (*_206)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_unlock;
const struct ossl_param_st* (* (*_207)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_gettable_params;
const struct ossl_param_st* (* (*_208)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_rand_gettable_ctx_params;
const struct ossl_param_st* (* (*_209)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_rand_settable_ctx_params;
int (* (*_210)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_rand_get_params;
int (* (*_211)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_rand_get_ctx_params;
int (* (*_212)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_rand_set_ctx_params;
void (* (*_213)(const struct ossl_dispatch_st*))(void*, int (*)(struct ossl_param_st[], struct ossl_param_st[], void*), int (*)(struct ossl_param_st[], void*), int (*)(struct ossl_param_st[], struct ossl_param_st[], void*), int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_rand_set_callbacks;
int (* (*_214)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_rand_verify_zeroization;
unsigned long long (* (*_215)(const struct ossl_dispatch_st*))(void*, unsigned char**, int, unsigned long long, unsigned long long, int, const unsigned char*, unsigned long long) = &::OSSL_FUNC_rand_get_seed;
void (* (*_216)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long) = &::OSSL_FUNC_rand_clear_seed;
void* (* (*_217)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keymgmt_new;
void* (* (*_218)(const struct ossl_dispatch_st*))(void*, int, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_gen_init;
int (* (*_219)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keymgmt_gen_set_template;
int (* (*_220)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_gen_set_params;
const struct ossl_param_st* (* (*_221)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keymgmt_gen_settable_params;
int (* (*_222)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_gen_get_params;
const struct ossl_param_st* (* (*_223)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keymgmt_gen_gettable_params;
void* (* (*_224)(const struct ossl_dispatch_st*))(void*, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_keymgmt_gen;
void (* (*_225)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keymgmt_gen_cleanup;
void* (* (*_226)(const struct ossl_dispatch_st*))(const void*, unsigned long long) = &::OSSL_FUNC_keymgmt_load;
void (* (*_227)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keymgmt_free;
int (* (*_228)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_get_params;
const struct ossl_param_st* (* (*_229)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keymgmt_gettable_params;
int (* (*_230)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_set_params;
const struct ossl_param_st* (* (*_231)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keymgmt_settable_params;
const char* (* (*_232)(const struct ossl_dispatch_st*))(int) = &::OSSL_FUNC_keymgmt_query_operation_name;
int (* (*_233)(const struct ossl_dispatch_st*))(const void*, int) = &::OSSL_FUNC_keymgmt_has;
int (* (*_234)(const struct ossl_dispatch_st*))(const void*, int, int) = &::OSSL_FUNC_keymgmt_validate;
int (* (*_235)(const struct ossl_dispatch_st*))(const void*, const void*, int) = &::OSSL_FUNC_keymgmt_match;
int (* (*_236)(const struct ossl_dispatch_st*))(void*, int, struct ossl_param_st[]) = &::OSSL_FUNC_keymgmt_import;
const struct ossl_param_st* (* (*_237)(const struct ossl_dispatch_st*))(int) = &::OSSL_FUNC_keymgmt_import_types;
int (* (*_238)(const struct ossl_dispatch_st*))(void*, int, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_keymgmt_export;
const struct ossl_param_st* (* (*_239)(const struct ossl_dispatch_st*))(int) = &::OSSL_FUNC_keymgmt_export_types;
void* (* (*_240)(const struct ossl_dispatch_st*))(const void*, int) = &::OSSL_FUNC_keymgmt_dup;
const struct ossl_param_st* (* (*_241)(const struct ossl_dispatch_st*))(void*, int) = &::OSSL_FUNC_keymgmt_import_types_ex;
const struct ossl_param_st* (* (*_242)(const struct ossl_dispatch_st*))(void*, int) = &::OSSL_FUNC_keymgmt_export_types_ex;
void* (* (*_243)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keyexch_newctx;
int (* (*_244)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_keyexch_init;
int (* (*_245)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_keyexch_derive;
int (* (*_246)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keyexch_set_peer;
void (* (*_247)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keyexch_freectx;
void* (* (*_248)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_keyexch_dupctx;
int (* (*_249)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keyexch_set_ctx_params;
const struct ossl_param_st* (* (*_250)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keyexch_settable_ctx_params;
int (* (*_251)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_keyexch_get_ctx_params;
const struct ossl_param_st* (* (*_252)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_keyexch_gettable_ctx_params;
void* (* (*_253)(const struct ossl_dispatch_st*))(void*, const char*) = &::OSSL_FUNC_signature_newctx;
int (* (*_254)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_sign_init;
int (* (*_255)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_sign;
int (* (*_256)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_sign_message_init;
int (* (*_257)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_sign_message_update;
int (* (*_258)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_signature_sign_message_final;
int (* (*_259)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_verify_init;
int (* (*_260)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_verify;
int (* (*_261)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_verify_message_init;
int (* (*_262)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_verify_message_update;
int (* (*_263)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_signature_verify_message_final;
int (* (*_264)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_verify_recover_init;
int (* (*_265)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_verify_recover;
int (* (*_266)(const struct ossl_dispatch_st*))(void*, const char*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_digest_sign_init;
int (* (*_267)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_digest_sign_update;
int (* (*_268)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long) = &::OSSL_FUNC_signature_digest_sign_final;
int (* (*_269)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_digest_sign;
int (* (*_270)(const struct ossl_dispatch_st*))(void*, const char*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_digest_verify_init;
int (* (*_271)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_digest_verify_update;
int (* (*_272)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_digest_verify_final;
int (* (*_273)(const struct ossl_dispatch_st*))(void*, const unsigned char*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_signature_digest_verify;
void (* (*_274)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_signature_freectx;
void* (* (*_275)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_signature_dupctx;
int (* (*_276)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_get_ctx_params;
const struct ossl_param_st* (* (*_277)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_signature_gettable_ctx_params;
int (* (*_278)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_set_ctx_params;
const struct ossl_param_st* (* (*_279)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_signature_settable_ctx_params;
int (* (*_280)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_get_ctx_md_params;
const struct ossl_param_st* (* (*_281)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_signature_gettable_ctx_md_params;
int (* (*_282)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_signature_set_ctx_md_params;
const struct ossl_param_st* (* (*_283)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_signature_settable_ctx_md_params;
const char** (* (*_284)(const struct ossl_dispatch_st*))() = &::OSSL_FUNC_signature_query_key_types;
void (* (*_285)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_skeymgmt_free;
const struct ossl_param_st* (* (*_286)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_skeymgmt_imp_settable_params;
void* (* (*_287)(const struct ossl_dispatch_st*))(void*, int, struct ossl_param_st[]) = &::OSSL_FUNC_skeymgmt_import;
int (* (*_288)(const struct ossl_dispatch_st*))(void*, int, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_skeymgmt_export;
const struct ossl_param_st* (* (*_289)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_skeymgmt_gen_settable_params;
void* (* (*_290)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_skeymgmt_generate;
const char* (* (*_291)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_skeymgmt_get_key_id;
void* (* (*_292)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_asym_cipher_newctx;
int (* (*_293)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_asym_cipher_encrypt_init;
int (* (*_294)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_asym_cipher_encrypt;
int (* (*_295)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_asym_cipher_decrypt_init;
int (* (*_296)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned long long, const unsigned char*, unsigned long long) = &::OSSL_FUNC_asym_cipher_decrypt;
void (* (*_297)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_asym_cipher_freectx;
void* (* (*_298)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_asym_cipher_dupctx;
int (* (*_299)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_asym_cipher_get_ctx_params;
const struct ossl_param_st* (* (*_300)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_asym_cipher_gettable_ctx_params;
int (* (*_301)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_asym_cipher_set_ctx_params;
const struct ossl_param_st* (* (*_302)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_asym_cipher_settable_ctx_params;
void* (* (*_303)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kem_newctx;
int (* (*_304)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_encapsulate_init;
int (* (*_305)(const struct ossl_dispatch_st*))(void*, void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_auth_encapsulate_init;
int (* (*_306)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, unsigned char*, unsigned long long*) = &::OSSL_FUNC_kem_encapsulate;
int (* (*_307)(const struct ossl_dispatch_st*))(void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_decapsulate_init;
int (* (*_308)(const struct ossl_dispatch_st*))(void*, void*, void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_auth_decapsulate_init;
int (* (*_309)(const struct ossl_dispatch_st*))(void*, unsigned char*, unsigned long long*, const unsigned char*, unsigned long long) = &::OSSL_FUNC_kem_decapsulate;
void (* (*_310)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kem_freectx;
void* (* (*_311)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_kem_dupctx;
int (* (*_312)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_get_ctx_params;
const struct ossl_param_st* (* (*_313)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_kem_gettable_ctx_params;
int (* (*_314)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_kem_set_ctx_params;
const struct ossl_param_st* (* (*_315)(const struct ossl_dispatch_st*))(void*, void*) = &::OSSL_FUNC_kem_settable_ctx_params;
void* (* (*_316)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_encoder_newctx;
void (* (*_317)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_encoder_freectx;
int (* (*_318)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_encoder_get_params;
const struct ossl_param_st* (* (*_319)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_encoder_gettable_params;
int (* (*_320)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_encoder_set_ctx_params;
const struct ossl_param_st* (* (*_321)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_encoder_settable_ctx_params;
int (* (*_322)(const struct ossl_dispatch_st*))(void*, int) = &::OSSL_FUNC_encoder_does_selection;
int (* (*_323)(const struct ossl_dispatch_st*))(void*, struct ossl_core_bio_st*, const void*, struct ossl_param_st[], int, int (*)(char*, unsigned long long, unsigned long long*, struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_encoder_encode;
void* (* (*_324)(const struct ossl_dispatch_st*))(void*, int, struct ossl_param_st[]) = &::OSSL_FUNC_encoder_import_object;
void (* (*_325)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_encoder_free_object;
void* (* (*_326)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_decoder_newctx;
void (* (*_327)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_decoder_freectx;
int (* (*_328)(const struct ossl_dispatch_st*))(struct ossl_param_st[]) = &::OSSL_FUNC_decoder_get_params;
const struct ossl_param_st* (* (*_329)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_decoder_gettable_params;
int (* (*_330)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_decoder_set_ctx_params;
const struct ossl_param_st* (* (*_331)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_decoder_settable_ctx_params;
int (* (*_332)(const struct ossl_dispatch_st*))(void*, int) = &::OSSL_FUNC_decoder_does_selection;
int (* (*_333)(const struct ossl_dispatch_st*))(void*, struct ossl_core_bio_st*, int, int (*)(struct ossl_param_st[], void*), void*, int (*)(char*, unsigned long long, unsigned long long*, struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_decoder_decode;
int (* (*_334)(const struct ossl_dispatch_st*))(void*, const void*, unsigned long long, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_decoder_export_object;
void* (* (*_335)(const struct ossl_dispatch_st*))(void*, const char*) = &::OSSL_FUNC_store_open;
void* (* (*_336)(const struct ossl_dispatch_st*))(void*, struct ossl_core_bio_st*) = &::OSSL_FUNC_store_attach;
const struct ossl_param_st* (* (*_337)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_store_settable_ctx_params;
int (* (*_338)(const struct ossl_dispatch_st*))(void*, struct ossl_param_st[]) = &::OSSL_FUNC_store_set_ctx_params;
int (* (*_339)(const struct ossl_dispatch_st*))(void*, int (*)(struct ossl_param_st[], void*), void*, int (*)(char*, unsigned long long, unsigned long long*, struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_store_load;
int (* (*_340)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_store_eof;
int (* (*_341)(const struct ossl_dispatch_st*))(void*) = &::OSSL_FUNC_store_close;
int (* (*_342)(const struct ossl_dispatch_st*))(void*, const void*, unsigned long long, int (*)(struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_store_export_object;
int (* (*_343)(const struct ossl_dispatch_st*))(void*, const char*, struct ossl_param_st[], int (*)(char*, unsigned long long, unsigned long long*, struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_store_delete;
void* (* (*_344)(const struct ossl_dispatch_st*))(void*, const char*, struct ossl_param_st[], int (*)(char*, unsigned long long, unsigned long long*, struct ossl_param_st[], void*), void*) = &::OSSL_FUNC_store_open_ex;
EVP_CTRL_TLS1_1_MULTIBLOCK_PARAM& (EVP_CTRL_TLS1_1_MULTIBLOCK_PARAM::*_345)(EVP_CTRL_TLS1_1_MULTIBLOCK_PARAM&&) = &EVP_CTRL_TLS1_1_MULTIBLOCK_PARAM::operator=;
struct evp_cipher_info_st& (evp_cipher_info_st::*_346)(struct evp_cipher_info_st&&) = &evp_cipher_info_st::operator=;
struct asn1_string_st& (asn1_string_st::*_347)(struct asn1_string_st&&) = &asn1_string_st::operator=;
struct ASN1_ENCODING_st& (ASN1_ENCODING_st::*_348)(struct ASN1_ENCODING_st&&) = &ASN1_ENCODING_st::operator=;
struct asn1_string_table_st& (asn1_string_table_st::*_349)(struct asn1_string_table_st&&) = &asn1_string_table_st::operator=;
struct asn1_type_st& (asn1_type_st::*_350)(struct asn1_type_st&&) = &asn1_type_st::operator=;
struct BIT_STRING_BITNAME_st& (BIT_STRING_BITNAME_st::*_351)(struct BIT_STRING_BITNAME_st&&) = &BIT_STRING_BITNAME_st::operator=;
void (*_352)(void (*)(void*), void*) = &::sk_X509_ALGOR_freefunc_thunk;
struct X509_algor_st* (*_353)(struct X509_algor_st*) = &::ossl_check_X509_ALGOR_type;
const struct stack_st* (*_354)(const struct stack_st_X509_ALGOR*) = &::ossl_check_const_X509_ALGOR_sk_type;
struct stack_st* (*_355)(struct stack_st_X509_ALGOR*) = &::ossl_check_X509_ALGOR_sk_type;
int (* (*_356)(int (*)(const struct X509_algor_st* const*, const struct X509_algor_st* const*)))(const void*, const void*) = &::ossl_check_X509_ALGOR_compfunc_type;
void* (* (*_357)(struct X509_algor_st* (*)(const struct X509_algor_st*)))(const void*) = &::ossl_check_X509_ALGOR_copyfunc_type;
void (* (*_358)(void (*)(struct X509_algor_st*)))(void*) = &::ossl_check_X509_ALGOR_freefunc_type;
void (*_359)(void (*)(void*), void*) = &::sk_ASN1_STRING_TABLE_freefunc_thunk;
struct asn1_string_table_st* (*_360)(struct asn1_string_table_st*) = &::ossl_check_ASN1_STRING_TABLE_type;
const struct stack_st* (*_361)(const struct stack_st_ASN1_STRING_TABLE*) = &::ossl_check_const_ASN1_STRING_TABLE_sk_type;
struct stack_st* (*_362)(struct stack_st_ASN1_STRING_TABLE*) = &::ossl_check_ASN1_STRING_TABLE_sk_type;
int (* (*_363)(int (*)(const struct asn1_string_table_st* const*, const struct asn1_string_table_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_STRING_TABLE_compfunc_type;
void* (* (*_364)(struct asn1_string_table_st* (*)(const struct asn1_string_table_st*)))(const void*) = &::ossl_check_ASN1_STRING_TABLE_copyfunc_type;
void (* (*_365)(void (*)(struct asn1_string_table_st*)))(void*) = &::ossl_check_ASN1_STRING_TABLE_freefunc_type;
void (*_366)(void (*)(void*), void*) = &::sk_ASN1_TYPE_freefunc_thunk;
struct asn1_type_st* (*_367)(struct asn1_type_st*) = &::ossl_check_ASN1_TYPE_type;
const struct stack_st* (*_368)(const struct stack_st_ASN1_TYPE*) = &::ossl_check_const_ASN1_TYPE_sk_type;
struct stack_st* (*_369)(struct stack_st_ASN1_TYPE*) = &::ossl_check_ASN1_TYPE_sk_type;
int (* (*_370)(int (*)(const struct asn1_type_st* const*, const struct asn1_type_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_TYPE_compfunc_type;
void* (* (*_371)(struct asn1_type_st* (*)(const struct asn1_type_st*)))(const void*) = &::ossl_check_ASN1_TYPE_copyfunc_type;
void (* (*_372)(void (*)(struct asn1_type_st*)))(void*) = &::ossl_check_ASN1_TYPE_freefunc_type;
void (*_373)(void (*)(void*), void*) = &::sk_ASN1_OBJECT_freefunc_thunk;
struct asn1_object_st* (*_374)(struct asn1_object_st*) = &::ossl_check_ASN1_OBJECT_type;
const struct stack_st* (*_375)(const struct stack_st_ASN1_OBJECT*) = &::ossl_check_const_ASN1_OBJECT_sk_type;
struct stack_st* (*_376)(struct stack_st_ASN1_OBJECT*) = &::ossl_check_ASN1_OBJECT_sk_type;
int (* (*_377)(int (*)(const struct asn1_object_st* const*, const struct asn1_object_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_OBJECT_compfunc_type;
void* (* (*_378)(struct asn1_object_st* (*)(const struct asn1_object_st*)))(const void*) = &::ossl_check_ASN1_OBJECT_copyfunc_type;
void (* (*_379)(void (*)(struct asn1_object_st*)))(void*) = &::ossl_check_ASN1_OBJECT_freefunc_type;
void (*_380)(void (*)(void*), void*) = &::sk_ASN1_INTEGER_freefunc_thunk;
struct asn1_string_st* (*_381)(struct asn1_string_st*) = &::ossl_check_ASN1_INTEGER_type;
const struct stack_st* (*_382)(const struct stack_st_ASN1_INTEGER*) = &::ossl_check_const_ASN1_INTEGER_sk_type;
struct stack_st* (*_383)(struct stack_st_ASN1_INTEGER*) = &::ossl_check_ASN1_INTEGER_sk_type;
int (* (*_384)(int (*)(const struct asn1_string_st* const*, const struct asn1_string_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_INTEGER_compfunc_type;
void* (* (*_385)(struct asn1_string_st* (*)(const struct asn1_string_st*)))(const void*) = &::ossl_check_ASN1_INTEGER_copyfunc_type;
void (* (*_386)(void (*)(struct asn1_string_st*)))(void*) = &::ossl_check_ASN1_INTEGER_freefunc_type;
void (*_387)(void (*)(void*), void*) = &::sk_ASN1_UTF8STRING_freefunc_thunk;
struct asn1_string_st* (*_388)(struct asn1_string_st*) = &::ossl_check_ASN1_UTF8STRING_type;
const struct stack_st* (*_389)(const struct stack_st_ASN1_UTF8STRING*) = &::ossl_check_const_ASN1_UTF8STRING_sk_type;
struct stack_st* (*_390)(struct stack_st_ASN1_UTF8STRING*) = &::ossl_check_ASN1_UTF8STRING_sk_type;
int (* (*_391)(int (*)(const struct asn1_string_st* const*, const struct asn1_string_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_UTF8STRING_compfunc_type;
void* (* (*_392)(struct asn1_string_st* (*)(const struct asn1_string_st*)))(const void*) = &::ossl_check_ASN1_UTF8STRING_copyfunc_type;
void (* (*_393)(void (*)(struct asn1_string_st*)))(void*) = &::ossl_check_ASN1_UTF8STRING_freefunc_type;
void (*_394)(void (*)(void*), void*) = &::sk_ASN1_GENERALSTRING_freefunc_thunk;
struct asn1_string_st* (*_395)(struct asn1_string_st*) = &::ossl_check_ASN1_GENERALSTRING_type;
const struct stack_st* (*_396)(const struct stack_st_ASN1_GENERALSTRING*) = &::ossl_check_const_ASN1_GENERALSTRING_sk_type;
struct stack_st* (*_397)(struct stack_st_ASN1_GENERALSTRING*) = &::ossl_check_ASN1_GENERALSTRING_sk_type;
int (* (*_398)(int (*)(const struct asn1_string_st* const*, const struct asn1_string_st* const*)))(const void*, const void*) = &::ossl_check_ASN1_GENERALSTRING_compfunc_type;
void* (* (*_399)(struct asn1_string_st* (*)(const struct asn1_string_st*)))(const void*) = &::ossl_check_ASN1_GENERALSTRING_copyfunc_type;
void (* (*_400)(void (*)(struct asn1_string_st*)))(void*) = &::ossl_check_ASN1_GENERALSTRING_freefunc_type;
struct obj_name_st& (obj_name_st::*_401)(struct obj_name_st&&) = &obj_name_st::operator=;
EC_builtin_curve& (EC_builtin_curve::*_402)(EC_builtin_curve&&) = &EC_builtin_curve::operator=;
struct rsa_pss_params_st& (rsa_pss_params_st::*_403)(struct rsa_pss_params_st&&) = &rsa_pss_params_st::operator=;
struct rsa_oaep_params_st& (rsa_oaep_params_st::*_404)(struct rsa_oaep_params_st&&) = &rsa_oaep_params_st::operator=;
struct SHAstate_st& (SHAstate_st::*_405)(struct SHAstate_st&&) = &SHAstate_st::operator=;
struct SHA256state_st& (SHA256state_st::*_406)(struct SHA256state_st&&) = &SHA256state_st::operator=;
struct SHA512state_st& (SHA512state_st::*_407)(struct SHA512state_st&&) = &SHA512state_st::operator=;
struct X509_algor_st& (X509_algor_st::*_408)(struct X509_algor_st&&) = &X509_algor_st::operator=;
struct X509_val_st& (X509_val_st::*_409)(struct X509_val_st&&) = &X509_val_st::operator=;
struct private_key_st& (private_key_st::*_410)(struct private_key_st&&) = &private_key_st::operator=;
struct X509_info_st& (X509_info_st::*_411)(struct X509_info_st&&) = &X509_info_st::operator=;
struct Netscape_spkac_st& (Netscape_spkac_st::*_412)(struct Netscape_spkac_st&&) = &Netscape_spkac_st::operator=;
struct Netscape_spki_st& (Netscape_spki_st::*_413)(struct Netscape_spki_st&&) = &Netscape_spki_st::operator=;
struct Netscape_certificate_sequence& (Netscape_certificate_sequence::*_414)(struct Netscape_certificate_sequence&&) = &Netscape_certificate_sequence::operator=;
struct PBEPARAM_st& (PBEPARAM_st::*_415)(struct PBEPARAM_st&&) = &PBEPARAM_st::operator=;
struct PBE2PARAM_st& (PBE2PARAM_st::*_416)(struct PBE2PARAM_st&&) = &PBE2PARAM_st::operator=;
struct PBKDF2PARAM_st& (PBKDF2PARAM_st::*_417)(struct PBKDF2PARAM_st&&) = &PBKDF2PARAM_st::operator=;
PBMAC1PARAM& (PBMAC1PARAM::*_418)(PBMAC1PARAM&&) = &PBMAC1PARAM::operator=;
struct SCRYPT_PARAMS_st& (SCRYPT_PARAMS_st::*_419)(struct SCRYPT_PARAMS_st&&) = &SCRYPT_PARAMS_st::operator=;
void (*_420)(void (*)(void*), void*) = &::sk_X509_NAME_freefunc_thunk;
struct X509_name_st* (*_421)(struct X509_name_st*) = &::ossl_check_X509_NAME_type;
const struct stack_st* (*_422)(const struct stack_st_X509_NAME*) = &::ossl_check_const_X509_NAME_sk_type;
struct stack_st* (*_423)(struct stack_st_X509_NAME*) = &::ossl_check_X509_NAME_sk_type;
int (* (*_424)(int (*)(const struct X509_name_st* const*, const struct X509_name_st* const*)))(const void*, const void*) = &::ossl_check_X509_NAME_compfunc_type;
void* (* (*_425)(struct X509_name_st* (*)(const struct X509_name_st*)))(const void*) = &::ossl_check_X509_NAME_copyfunc_type;
void (* (*_426)(void (*)(struct X509_name_st*)))(void*) = &::ossl_check_X509_NAME_freefunc_type;
void (*_427)(void (*)(void*), void*) = &::sk_X509_freefunc_thunk;
struct x509_st* (*_428)(struct x509_st*) = &::ossl_check_X509_type;
const struct stack_st* (*_429)(const struct stack_st_X509*) = &::ossl_check_const_X509_sk_type;
struct stack_st* (*_430)(struct stack_st_X509*) = &::ossl_check_X509_sk_type;
int (* (*_431)(int (*)(const struct x509_st* const*, const struct x509_st* const*)))(const void*, const void*) = &::ossl_check_X509_compfunc_type;
void* (* (*_432)(struct x509_st* (*)(const struct x509_st*)))(const void*) = &::ossl_check_X509_copyfunc_type;
void (* (*_433)(void (*)(struct x509_st*)))(void*) = &::ossl_check_X509_freefunc_type;
void (*_434)(void (*)(void*), void*) = &::sk_X509_REVOKED_freefunc_thunk;
struct x509_revoked_st* (*_435)(struct x509_revoked_st*) = &::ossl_check_X509_REVOKED_type;
const struct stack_st* (*_436)(const struct stack_st_X509_REVOKED*) = &::ossl_check_const_X509_REVOKED_sk_type;
struct stack_st* (*_437)(struct stack_st_X509_REVOKED*) = &::ossl_check_X509_REVOKED_sk_type;
int (* (*_438)(int (*)(const struct x509_revoked_st* const*, const struct x509_revoked_st* const*)))(const void*, const void*) = &::ossl_check_X509_REVOKED_compfunc_type;
void* (* (*_439)(struct x509_revoked_st* (*)(const struct x509_revoked_st*)))(const void*) = &::ossl_check_X509_REVOKED_copyfunc_type;
void (* (*_440)(void (*)(struct x509_revoked_st*)))(void*) = &::ossl_check_X509_REVOKED_freefunc_type;
void (*_441)(void (*)(void*), void*) = &::sk_X509_CRL_freefunc_thunk;
struct X509_crl_st* (*_442)(struct X509_crl_st*) = &::ossl_check_X509_CRL_type;
const struct stack_st* (*_443)(const struct stack_st_X509_CRL*) = &::ossl_check_const_X509_CRL_sk_type;
struct stack_st* (*_444)(struct stack_st_X509_CRL*) = &::ossl_check_X509_CRL_sk_type;
int (* (*_445)(int (*)(const struct X509_crl_st* const*, const struct X509_crl_st* const*)))(const void*, const void*) = &::ossl_check_X509_CRL_compfunc_type;
void* (* (*_446)(struct X509_crl_st* (*)(const struct X509_crl_st*)))(const void*) = &::ossl_check_X509_CRL_copyfunc_type;
void (* (*_447)(void (*)(struct X509_crl_st*)))(void*) = &::ossl_check_X509_CRL_freefunc_type;
void (*_448)(void (*)(void*), void*) = &::sk_X509_NAME_ENTRY_freefunc_thunk;
struct X509_name_entry_st* (*_449)(struct X509_name_entry_st*) = &::ossl_check_X509_NAME_ENTRY_type;
const struct stack_st* (*_450)(const struct stack_st_X509_NAME_ENTRY*) = &::ossl_check_const_X509_NAME_ENTRY_sk_type;
struct stack_st* (*_451)(struct stack_st_X509_NAME_ENTRY*) = &::ossl_check_X509_NAME_ENTRY_sk_type;
int (* (*_452)(int (*)(const struct X509_name_entry_st* const*, const struct X509_name_entry_st* const*)))(const void*, const void*) = &::ossl_check_X509_NAME_ENTRY_compfunc_type;
void* (* (*_453)(struct X509_name_entry_st* (*)(const struct X509_name_entry_st*)))(const void*) = &::ossl_check_X509_NAME_ENTRY_copyfunc_type;
void (* (*_454)(void (*)(struct X509_name_entry_st*)))(void*) = &::ossl_check_X509_NAME_ENTRY_freefunc_type;
void (*_455)(void (*)(void*), void*) = &::sk_X509_EXTENSION_freefunc_thunk;
struct X509_extension_st* (*_456)(struct X509_extension_st*) = &::ossl_check_X509_EXTENSION_type;
const struct stack_st* (*_457)(const struct stack_st_X509_EXTENSION*) = &::ossl_check_const_X509_EXTENSION_sk_type;
struct stack_st* (*_458)(struct stack_st_X509_EXTENSION*) = &::ossl_check_X509_EXTENSION_sk_type;
int (* (*_459)(int (*)(const struct X509_extension_st* const*, const struct X509_extension_st* const*)))(const void*, const void*) = &::ossl_check_X509_EXTENSION_compfunc_type;
void* (* (*_460)(struct X509_extension_st* (*)(const struct X509_extension_st*)))(const void*) = &::ossl_check_X509_EXTENSION_copyfunc_type;
void (* (*_461)(void (*)(struct X509_extension_st*)))(void*) = &::ossl_check_X509_EXTENSION_freefunc_type;
void (*_462)(void (*)(void*), void*) = &::sk_X509_ATTRIBUTE_freefunc_thunk;
struct x509_attributes_st* (*_463)(struct x509_attributes_st*) = &::ossl_check_X509_ATTRIBUTE_type;
const struct stack_st* (*_464)(const struct stack_st_X509_ATTRIBUTE*) = &::ossl_check_const_X509_ATTRIBUTE_sk_type;
struct stack_st* (*_465)(struct stack_st_X509_ATTRIBUTE*) = &::ossl_check_X509_ATTRIBUTE_sk_type;
int (* (*_466)(int (*)(const struct x509_attributes_st* const*, const struct x509_attributes_st* const*)))(const void*, const void*) = &::ossl_check_X509_ATTRIBUTE_compfunc_type;
void* (* (*_467)(struct x509_attributes_st* (*)(const struct x509_attributes_st*)))(const void*) = &::ossl_check_X509_ATTRIBUTE_copyfunc_type;
void (* (*_468)(void (*)(struct x509_attributes_st*)))(void*) = &::ossl_check_X509_ATTRIBUTE_freefunc_type;
void (*_469)(void (*)(void*), void*) = &::sk_X509_INFO_freefunc_thunk;
struct X509_info_st* (*_470)(struct X509_info_st*) = &::ossl_check_X509_INFO_type;
const struct stack_st* (*_471)(const struct stack_st_X509_INFO*) = &::ossl_check_const_X509_INFO_sk_type;
struct stack_st* (*_472)(struct stack_st_X509_INFO*) = &::ossl_check_X509_INFO_sk_type;
int (* (*_473)(int (*)(const struct X509_info_st* const*, const struct X509_info_st* const*)))(const void*, const void*) = &::ossl_check_X509_INFO_compfunc_type;
void* (* (*_474)(struct X509_info_st* (*)(const struct X509_info_st*)))(const void*) = &::ossl_check_X509_INFO_copyfunc_type;
void (* (*_475)(void (*)(struct X509_info_st*)))(void*) = &::ossl_check_X509_INFO_freefunc_type;
struct x509_trust_st& (x509_trust_st::*_476)(struct x509_trust_st&&) = &x509_trust_st::operator=;
void (*_477)(void (*)(void*), void*) = &::sk_X509_LOOKUP_freefunc_thunk;
struct x509_lookup_st* (*_478)(struct x509_lookup_st*) = &::ossl_check_X509_LOOKUP_type;
const struct stack_st* (*_479)(const struct stack_st_X509_LOOKUP*) = &::ossl_check_const_X509_LOOKUP_sk_type;
struct stack_st* (*_480)(struct stack_st_X509_LOOKUP*) = &::ossl_check_X509_LOOKUP_sk_type;
int (* (*_481)(int (*)(const struct x509_lookup_st* const*, const struct x509_lookup_st* const*)))(const void*, const void*) = &::ossl_check_X509_LOOKUP_compfunc_type;
void* (* (*_482)(struct x509_lookup_st* (*)(const struct x509_lookup_st*)))(const void*) = &::ossl_check_X509_LOOKUP_copyfunc_type;
void (* (*_483)(void (*)(struct x509_lookup_st*)))(void*) = &::ossl_check_X509_LOOKUP_freefunc_type;
void (*_484)(void (*)(void*), void*) = &::sk_X509_OBJECT_freefunc_thunk;
struct x509_object_st* (*_485)(struct x509_object_st*) = &::ossl_check_X509_OBJECT_type;
const struct stack_st* (*_486)(const struct stack_st_X509_OBJECT*) = &::ossl_check_const_X509_OBJECT_sk_type;
struct stack_st* (*_487)(struct stack_st_X509_OBJECT*) = &::ossl_check_X509_OBJECT_sk_type;
int (* (*_488)(int (*)(const struct x509_object_st* const*, const struct x509_object_st* const*)))(const void*, const void*) = &::ossl_check_X509_OBJECT_compfunc_type;
void* (* (*_489)(struct x509_object_st* (*)(const struct x509_object_st*)))(const void*) = &::ossl_check_X509_OBJECT_copyfunc_type;
void (* (*_490)(void (*)(struct x509_object_st*)))(void*) = &::ossl_check_X509_OBJECT_freefunc_type;
void (*_491)(void (*)(void*), void*) = &::sk_X509_VERIFY_PARAM_freefunc_thunk;
struct X509_VERIFY_PARAM_st* (*_492)(struct X509_VERIFY_PARAM_st*) = &::ossl_check_X509_VERIFY_PARAM_type;
const struct stack_st* (*_493)(const struct stack_st_X509_VERIFY_PARAM*) = &::ossl_check_const_X509_VERIFY_PARAM_sk_type;
struct stack_st* (*_494)(struct stack_st_X509_VERIFY_PARAM*) = &::ossl_check_X509_VERIFY_PARAM_sk_type;
int (* (*_495)(int (*)(const struct X509_VERIFY_PARAM_st* const*, const struct X509_VERIFY_PARAM_st* const*)))(const void*, const void*) = &::ossl_check_X509_VERIFY_PARAM_compfunc_type;
void* (* (*_496)(struct X509_VERIFY_PARAM_st* (*)(const struct X509_VERIFY_PARAM_st*)))(const void*) = &::ossl_check_X509_VERIFY_PARAM_copyfunc_type;
void (* (*_497)(void (*)(struct X509_VERIFY_PARAM_st*)))(void*) = &::ossl_check_X509_VERIFY_PARAM_freefunc_type;
void (*_498)(void (*)(void*), void*) = &::sk_X509_TRUST_freefunc_thunk;
struct x509_trust_st* (*_499)(struct x509_trust_st*) = &::ossl_check_X509_TRUST_type;
const struct stack_st* (*_500)(const struct stack_st_X509_TRUST*) = &::ossl_check_const_X509_TRUST_sk_type;
struct stack_st* (*_501)(struct stack_st_X509_TRUST*) = &::ossl_check_X509_TRUST_sk_type;
int (* (*_502)(int (*)(const struct x509_trust_st* const*, const struct x509_trust_st* const*)))(const void*, const void*) = &::ossl_check_X509_TRUST_compfunc_type;
void* (* (*_503)(struct x509_trust_st* (*)(const struct x509_trust_st*)))(const void*) = &::ossl_check_X509_TRUST_copyfunc_type;
void (* (*_504)(void (*)(struct x509_trust_st*)))(void*) = &::ossl_check_X509_TRUST_freefunc_type;
union lhash_st_OPENSSL_STRING::lh_OPENSSL_STRING_dummy& (lhash_st_OPENSSL_STRING::lh_OPENSSL_STRING_dummy::*_505)(union lhash_st_OPENSSL_STRING::lh_OPENSSL_STRING_dummy&&) = &lhash_st_OPENSSL_STRING::lh_OPENSSL_STRING_dummy::operator=;
struct lhash_st_OPENSSL_STRING& (lhash_st_OPENSSL_STRING::*_506)(struct lhash_st_OPENSSL_STRING&&) = &lhash_st_OPENSSL_STRING::operator=;
union lhash_st_OPENSSL_CSTRING::lh_OPENSSL_CSTRING_dummy& (lhash_st_OPENSSL_CSTRING::lh_OPENSSL_CSTRING_dummy::*_507)(union lhash_st_OPENSSL_CSTRING::lh_OPENSSL_CSTRING_dummy&&) = &lhash_st_OPENSSL_CSTRING::lh_OPENSSL_CSTRING_dummy::operator=;
struct lhash_st_OPENSSL_CSTRING& (lhash_st_OPENSSL_CSTRING::*_508)(struct lhash_st_OPENSSL_CSTRING&&) = &lhash_st_OPENSSL_CSTRING::operator=;
unsigned long (*_509)(const void*, unsigned long (*)(const void*)) = &::lh_OPENSSL_STRING_hash_thunk;
int (*_510)(const void*, const void*, int (*)(const void*, const void*)) = &::lh_OPENSSL_STRING_comp_thunk;
void (*_511)(void*, void (*)(void*)) = &::lh_OPENSSL_STRING_doall_thunk;
void (*_512)(void*, void*, void (*)(void*, void*)) = &::lh_OPENSSL_STRING_doall_arg_thunk;
char** (*_513)(char**) = &::ossl_check_OPENSSL_STRING_lh_plain_type;
const char** (*_514)(const char**) = &::ossl_check_const_OPENSSL_STRING_lh_plain_type;
const struct lhash_st* (*_515)(const struct lhash_st_OPENSSL_STRING*) = &::ossl_check_const_OPENSSL_STRING_lh_type;
struct lhash_st* (*_516)(struct lhash_st_OPENSSL_STRING*) = &::ossl_check_OPENSSL_STRING_lh_type;
int (* (*_517)(int (*)(const char**, const char**)))(const void*, const void*) = &::ossl_check_OPENSSL_STRING_lh_compfunc_type;
unsigned long (* (*_518)(unsigned long (*)(const char**)))(const void*) = &::ossl_check_OPENSSL_STRING_lh_hashfunc_type;
void (* (*_519)(void (*)(char**)))(void*) = &::ossl_check_OPENSSL_STRING_lh_doallfunc_type;
unsigned long (*_520)(const void*, unsigned long (*)(const void*)) = &::lh_OPENSSL_CSTRING_hash_thunk;
int (*_521)(const void*, const void*, int (*)(const void*, const void*)) = &::lh_OPENSSL_CSTRING_comp_thunk;
void (*_522)(void*, void (*)(void*)) = &::lh_OPENSSL_CSTRING_doall_thunk;
void (*_523)(void*, void*, void (*)(void*, void*)) = &::lh_OPENSSL_CSTRING_doall_arg_thunk;
const char** (*_524)(const char**) = &::ossl_check_OPENSSL_CSTRING_lh_plain_type;
const const char** (*_525)(const const char**) = &::ossl_check_const_OPENSSL_CSTRING_lh_plain_type;
const struct lhash_st* (*_526)(const struct lhash_st_OPENSSL_CSTRING*) = &::ossl_check_const_OPENSSL_CSTRING_lh_type;
struct lhash_st* (*_527)(struct lhash_st_OPENSSL_CSTRING*) = &::ossl_check_OPENSSL_CSTRING_lh_type;
int (* (*_528)(int (*)(const const char**, const const char**)))(const void*, const void*) = &::ossl_check_OPENSSL_CSTRING_lh_compfunc_type;
unsigned long (* (*_529)(unsigned long (*)(const const char**)))(const void*) = &::ossl_check_OPENSSL_CSTRING_lh_hashfunc_type;
void (* (*_530)(void (*)(const char**)))(void*) = &::ossl_check_OPENSSL_CSTRING_lh_doallfunc_type;
struct PKCS7_CTX_st& (PKCS7_CTX_st::*_531)(struct PKCS7_CTX_st&&) = &PKCS7_CTX_st::operator=;
struct pkcs7_issuer_and_serial_st& (pkcs7_issuer_and_serial_st::*_532)(struct pkcs7_issuer_and_serial_st&&) = &pkcs7_issuer_and_serial_st::operator=;
struct pkcs7_signer_info_st& (pkcs7_signer_info_st::*_533)(struct pkcs7_signer_info_st&&) = &pkcs7_signer_info_st::operator=;
struct pkcs7_recip_info_st& (pkcs7_recip_info_st::*_534)(struct pkcs7_recip_info_st&&) = &pkcs7_recip_info_st::operator=;
struct pkcs7_signed_st& (pkcs7_signed_st::*_535)(struct pkcs7_signed_st&&) = &pkcs7_signed_st::operator=;
struct pkcs7_enc_content_st& (pkcs7_enc_content_st::*_536)(struct pkcs7_enc_content_st&&) = &pkcs7_enc_content_st::operator=;
struct pkcs7_enveloped_st& (pkcs7_enveloped_st::*_537)(struct pkcs7_enveloped_st&&) = &pkcs7_enveloped_st::operator=;
struct pkcs7_signedandenveloped_st& (pkcs7_signedandenveloped_st::*_538)(struct pkcs7_signedandenveloped_st&&) = &pkcs7_signedandenveloped_st::operator=;
struct pkcs7_digest_st& (pkcs7_digest_st::*_539)(struct pkcs7_digest_st&&) = &pkcs7_digest_st::operator=;
struct pkcs7_encrypted_st& (pkcs7_encrypted_st::*_540)(struct pkcs7_encrypted_st&&) = &pkcs7_encrypted_st::operator=;
struct pkcs7_st& (pkcs7_st::*_541)(struct pkcs7_st&&) = &pkcs7_st::operator=;
void (*_542)(void (*)(void*), void*) = &::sk_PKCS7_SIGNER_INFO_freefunc_thunk;
struct pkcs7_signer_info_st* (*_543)(struct pkcs7_signer_info_st*) = &::ossl_check_PKCS7_SIGNER_INFO_type;
const struct stack_st* (*_544)(const struct stack_st_PKCS7_SIGNER_INFO*) = &::ossl_check_const_PKCS7_SIGNER_INFO_sk_type;
struct stack_st* (*_545)(struct stack_st_PKCS7_SIGNER_INFO*) = &::ossl_check_PKCS7_SIGNER_INFO_sk_type;
int (* (*_546)(int (*)(const struct pkcs7_signer_info_st* const*, const struct pkcs7_signer_info_st* const*)))(const void*, const void*) = &::ossl_check_PKCS7_SIGNER_INFO_compfunc_type;
void* (* (*_547)(struct pkcs7_signer_info_st* (*)(const struct pkcs7_signer_info_st*)))(const void*) = &::ossl_check_PKCS7_SIGNER_INFO_copyfunc_type;
void (* (*_548)(void (*)(struct pkcs7_signer_info_st*)))(void*) = &::ossl_check_PKCS7_SIGNER_INFO_freefunc_type;
void (*_549)(void (*)(void*), void*) = &::sk_PKCS7_RECIP_INFO_freefunc_thunk;
struct pkcs7_recip_info_st* (*_550)(struct pkcs7_recip_info_st*) = &::ossl_check_PKCS7_RECIP_INFO_type;
const struct stack_st* (*_551)(const struct stack_st_PKCS7_RECIP_INFO*) = &::ossl_check_const_PKCS7_RECIP_INFO_sk_type;
struct stack_st* (*_552)(struct stack_st_PKCS7_RECIP_INFO*) = &::ossl_check_PKCS7_RECIP_INFO_sk_type;
int (* (*_553)(int (*)(const struct pkcs7_recip_info_st* const*, const struct pkcs7_recip_info_st* const*)))(const void*, const void*) = &::ossl_check_PKCS7_RECIP_INFO_compfunc_type;
void* (* (*_554)(struct pkcs7_recip_info_st* (*)(const struct pkcs7_recip_info_st*)))(const void*) = &::ossl_check_PKCS7_RECIP_INFO_copyfunc_type;
void (* (*_555)(void (*)(struct pkcs7_recip_info_st*)))(void*) = &::ossl_check_PKCS7_RECIP_INFO_freefunc_type;
void (*_556)(void (*)(void*), void*) = &::sk_PKCS7_freefunc_thunk;
struct pkcs7_st* (*_557)(struct pkcs7_st*) = &::ossl_check_PKCS7_type;
const struct stack_st* (*_558)(const struct stack_st_PKCS7*) = &::ossl_check_const_PKCS7_sk_type;
struct stack_st* (*_559)(struct stack_st_PKCS7*) = &::ossl_check_PKCS7_sk_type;
int (* (*_560)(int (*)(const struct pkcs7_st* const*, const struct pkcs7_st* const*)))(const void*, const void*) = &::ossl_check_PKCS7_compfunc_type;
void* (* (*_561)(struct pkcs7_st* (*)(const struct pkcs7_st*)))(const void*) = &::ossl_check_PKCS7_copyfunc_type;
void (* (*_562)(void (*)(struct pkcs7_st*)))(void*) = &::ossl_check_PKCS7_freefunc_type;
CONF_VALUE& (CONF_VALUE::*_563)(CONF_VALUE&&) = &CONF_VALUE::operator=;
union lhash_st_CONF_VALUE::lh_CONF_VALUE_dummy& (lhash_st_CONF_VALUE::lh_CONF_VALUE_dummy::*_564)(union lhash_st_CONF_VALUE::lh_CONF_VALUE_dummy&&) = &lhash_st_CONF_VALUE::lh_CONF_VALUE_dummy::operator=;
struct lhash_st_CONF_VALUE& (lhash_st_CONF_VALUE::*_565)(struct lhash_st_CONF_VALUE&&) = &lhash_st_CONF_VALUE::operator=;
struct conf_method_st& (conf_method_st::*_566)(struct conf_method_st&&) = &conf_method_st::operator=;
struct conf_st& (conf_st::*_567)(struct conf_st&&) = &conf_st::operator=;
void (*_568)(void (*)(void*), void*) = &::sk_CONF_VALUE_freefunc_thunk;
CONF_VALUE* (*_569)(CONF_VALUE*) = &::ossl_check_CONF_VALUE_type;
const struct stack_st* (*_570)(const struct stack_st_CONF_VALUE*) = &::ossl_check_const_CONF_VALUE_sk_type;
struct stack_st* (*_571)(struct stack_st_CONF_VALUE*) = &::ossl_check_CONF_VALUE_sk_type;
int (* (*_572)(int (*)(const CONF_VALUE* const*, const CONF_VALUE* const*)))(const void*, const void*) = &::ossl_check_CONF_VALUE_compfunc_type;
void* (* (*_573)(CONF_VALUE* (*)(const CONF_VALUE*)))(const void*) = &::ossl_check_CONF_VALUE_copyfunc_type;
void (* (*_574)(void (*)(CONF_VALUE*)))(void*) = &::ossl_check_CONF_VALUE_freefunc_type;
unsigned long (*_575)(const void*, unsigned long (*)(const void*)) = &::lh_CONF_VALUE_hash_thunk;
int (*_576)(const void*, const void*, int (*)(const void*, const void*)) = &::lh_CONF_VALUE_comp_thunk;
void (*_577)(void*, void (*)(void*)) = &::lh_CONF_VALUE_doall_thunk;
void (*_578)(void*, void*, void (*)(void*, void*)) = &::lh_CONF_VALUE_doall_arg_thunk;
CONF_VALUE* (*_579)(CONF_VALUE*) = &::ossl_check_CONF_VALUE_lh_plain_type;
const CONF_VALUE* (*_580)(const CONF_VALUE*) = &::ossl_check_const_CONF_VALUE_lh_plain_type;
const struct lhash_st* (*_581)(const struct lhash_st_CONF_VALUE*) = &::ossl_check_const_CONF_VALUE_lh_type;
struct lhash_st* (*_582)(struct lhash_st_CONF_VALUE*) = &::ossl_check_CONF_VALUE_lh_type;
int (* (*_583)(int (*)(const CONF_VALUE*, const CONF_VALUE*)))(const void*, const void*) = &::ossl_check_CONF_VALUE_lh_compfunc_type;
unsigned long (* (*_584)(unsigned long (*)(const CONF_VALUE*)))(const void*) = &::ossl_check_CONF_VALUE_lh_hashfunc_type;
void (* (*_585)(void (*)(CONF_VALUE*)))(void*) = &::ossl_check_CONF_VALUE_lh_doallfunc_type;
void (*_586)(void (*)(void*), void*) = &::sk_SCT_freefunc_thunk;
struct sct_st* (*_587)(struct sct_st*) = &::ossl_check_SCT_type;
const struct stack_st* (*_588)(const struct stack_st_SCT*) = &::ossl_check_const_SCT_sk_type;
struct stack_st* (*_589)(struct stack_st_SCT*) = &::ossl_check_SCT_sk_type;
int (* (*_590)(int (*)(const struct sct_st* const*, const struct sct_st* const*)))(const void*, const void*) = &::ossl_check_SCT_compfunc_type;
void* (* (*_591)(struct sct_st* (*)(const struct sct_st*)))(const void*) = &::ossl_check_SCT_copyfunc_type;
void (* (*_592)(void (*)(struct sct_st*)))(void*) = &::ossl_check_SCT_freefunc_type;
void (*_593)(void (*)(void*), void*) = &::sk_CTLOG_freefunc_thunk;
struct ctlog_st* (*_594)(struct ctlog_st*) = &::ossl_check_CTLOG_type;
const struct stack_st* (*_595)(const struct stack_st_CTLOG*) = &::ossl_check_const_CTLOG_sk_type;
struct stack_st* (*_596)(struct stack_st_CTLOG*) = &::ossl_check_CTLOG_sk_type;
int (* (*_597)(int (*)(const struct ctlog_st* const*, const struct ctlog_st* const*)))(const void*, const void*) = &::ossl_check_CTLOG_compfunc_type;
void* (* (*_598)(struct ctlog_st* (*)(const struct ctlog_st*)))(const void*) = &::ossl_check_CTLOG_copyfunc_type;
void (* (*_599)(void (*)(struct ctlog_st*)))(void*) = &::ossl_check_CTLOG_freefunc_type;
struct tls_session_ticket_ext_st& (tls_session_ticket_ext_st::*_600)(struct tls_session_ticket_ext_st&&) = &tls_session_ticket_ext_st::operator=;
