namespace AKNet.MSQuicWrapper
{
    public enum QUIC_LOAD_BALANCING_MODE
    {
        QUIC_LOAD_BALANCING_DISABLED,
        QUIC_LOAD_BALANCING_SERVER_ID_IP,
        QUIC_LOAD_BALANCING_SERVER_ID_FIXED,
        QUIC_LOAD_BALANCING_COUNT,
    }
}
